### ISSUE TITLE
Decidability not inferred unless namespace is open

### ISSUE THREAD

**Issue by htzh** [leanprover/lean3#683] opened 2015-06-18 01:31 UTC
In the following example:

```
section cyclic
variable {A : Type}
variable [finA : fintype A]
include finA
variable [deceqA : decidable_eq A]
include deceqA
variable [ambG : group A]
include ambG

open fintype nat fin

definition cyc (a : A) : finset A := {x ∈ univ | bex (card A) (λ n, a ^ n = x)}
--definition cyc₁ (a : A) : finset A := {x ∈ univ | ∃ n, a ^ n = x}
definition cyc₂ (a : A) : finset A := {x ∈ univ | ∃ (n : fin (card A)), a ^ n = x}
end cyclic
```

cyc₂ does not type check if fin namespace is not open with the following message:

```
failed to synthesize placeholder
A : Type,
finA : fintype A,
deceqA : decidable_eq A,
ambG : group A,
a : A
⊢ decidable_pred (λ (x : A), ∃ (n : fin (card A)), a ^ fin.val n = x)
```

My guess is that Lean can't see the `definition is_fintype [instance] (n : nat) : fintype (fin n)` which is defined inside the `fin` namespace. I wonder if this is desirable behavior. The problem itself is no big deal. We can work easily around by opening the namespace or bringing the instance outside of the namespace. But it seems to me that imported instances should be inferred independent of whether the namespace is open or not.

**Comment by avigad** [comment] 2015-06-18 01:41
As with other sorts of metadata (coercions, notation, reducibility declarations, etc.) namespaces give us a way to manage what is in play at any given point in our files. Why should instances be treated different from, say, coercions?

This isn't a rhetorical question. We often get confusing and unexpected behavior when something is hidden in a namespace, and I want things to be as natural and intuitive as possible. We generally want things to work "by default", but we also want (and need) the flexibility to manage a context.

**Comment by htzh** [comment] 2015-06-18 02:01
> Why should instances be treated different from, say, coercions?

Instances can be chained. Do the chained instances have to be in namespaces that are already open as well? If not we are already inferring instances that are not necessarily in an open namespace.

**Comment by avigad** [comment] 2015-06-18 02:16
Indeed, the chained instances have to be in namespaces that are already open. The `print instances` command shows all the instances that will be used.

This can cause unintuitive behavior, though. The issue seems to be similar to one that is being addressed in #668 with coercions. It seems more complex, though, for the reasons discussed in #666. (The `transitive-instances` partially addresses the problem, I suppose.)

**Comment by htzh** [comment] 2015-06-18 02:21
> but we also want (and need) the flexibility to manage a context.

I agree. For other content in a namespace one can always refer to them with their full name `ns.name`. However if in order for an instance to be inferred you need to open the namespace it actually forces you to expose a lot more internals than otherwise necessary. Either way would work in practice but I don't see a clear argument that instances should be hidden by default. Maybe there is a performance reason not to do so.

**Comment by fpvandoorn** [comment] 2015-06-18 02:28
I think performance is indeed the main reason to hide unused instances. Typically you have imported a lot of files (maybe almost all of the standard library when using `import standard`), but you don't need anything from different namespaces.

You can also open only the instances of a namespace using

```
open [classes] foo
```

This will keep all other data of that namespace hidden.

**Comment by htzh** [comment] 2015-06-18 02:31
I would also argue that hiding instances in unopened namespace is contrary to the semantics of namespace. We use import to control what facts are available. Objects in an unopened namespace are still available, just by their full names only. Since an inferred instance is not named in the first place, it seems to me that the logical way is that it will be inferred with the full name instead of being hidden. If we want to control the availability it seems we should devise a separate mechanism. This may also solve some of the other issues that @avigad mentioned.

**Comment by htzh** [comment] 2015-06-18 02:37
> You can also open only the instances of a namespace using
> open [classes] foo
> This will keep all other data of that namespace hidden.

@fpvandoorn good point. Thanks for the tip. The need of this particular device attests to the semantic issue that I argued in my last post. Hiding instances using namespace are conflating two things together: whether a fact is known by certain name and whether a fact is available at all.

**Comment by avigad** [comment] 2015-06-18 02:48
Again, namespaces are used not only for identifier names, but to manage attributes and other metadata: coercions, notation, rewrite rules, reducibility hints for the elaborator, ... So it would seem strange to devise another mechanism to control availability, when namespaces were designed exactly for that purpose. If the intention is that an instance should be available as soon as the file is imported, why not declare the instance at top level, outside the namespace?

Would it help to have a command like 

```
global attribute foo [instance]
```

where "global" means "declare this at top level, outside the current namespace"?

**Comment by htzh** [comment] 2015-06-18 03:09
I would argue that instances (at least in the way I use them) are indeed special. Things like coercions, notations are explicitly about names (you want a different way to say the same thing) and therefore it seems natural that namespace should control their behavior. Instances are specifically not about names. They carry implicit facts that mean the same thing whatever names they are called. I think that is what makes them nice in terms of interface: they are implicit properties of objects that hides the implementation details from the user and the user does not even need to know the name at all. Hiding it by default seems to break that abstraction. 

I would agree that in practice the difference may not be that important. It is likely the namespace is open if a user wants some objects from a namespace. But if the user somehow decides to not open the namespace (maybe so as not to clash with other names) the behavior could then be confusing. I think `global` would help. But would it be better the other way around? Use `local` if one truly does not want to make an instance available by default for performance reasons?

**Comment by avigad** [comment] 2015-06-18 03:27
In fact, we already have a `local` keyword (as in, `local attribute foo [instance]`). This means, "make the attribute operant in the current file or section only."

My biggest concern with the proposal is one of uniformity. Context management and availability issues come up in all sorts of ways -- attributes can have bearing on all sorts of automation, not just elaboration -- and the namespace / attributes / metadata approach aims to provide a principled and uniform way of handling this. It is a fairly simple story: we declare things in namespaces, and then open the namespaces to make them available. It will be confusing to users if most things handled one way, but the treatment of instances is different.

But there may be good reasons to make an exception. I am curious to hear other opinions.

**Comment by fpvandoorn** [comment] 2015-06-18 04:04
I like the proposal of a `global attribute` command.

Actually I've been thinking for a while about this issue for other attributes. For some attributes it doesn't make sense that they are unavailable if the namespace is not opened. Is it currently the case that all attributes are hidden if the namespace is not opened? For some attributes I think this is undesirable. The most striking example is perhaps the `[irreducible]` attribute. It would be strange that a identifier becomes _less_ reducible if I open its namespace. There are other attributes which would be better to always be globally available. I'm thinking of the unfold-hints `[unfold-c]`, `[unfold-m]`, `[constructor]`, calc-hints `[refl]`, `[symm]`, `[trans]`, `[subst]` and maybe also `[recursor]` and the other reduce-hints. 

Other attributes should clearly not be always available, we should hide `[coercion]` be default, because opening all coercions leads to performance issues, worse error messages and unexpected behavior. I think none of these issues are a problem for the above attributes (except maybe `[recursor]` and the reduce-hints)

I'm undecided whether `[instance]` can always be available. I'm afraid it causes performance issues like coercions, to a lesser extend. There are examples where type class inference is having trouble finding an instance, and giving it more (irrelevant) options might make that problem worse. For example [here](https://github.com/leanprover/lean/blob/master/hott/algebra/category/functor.hlean#L138-143) I had to give a particular instance locally a higher priority, because type class inference would fail without that. Another potential problem is that opening namespaces in different orders can cause type class inference to break, because the order of opening namespaces causes the order in which instances (with the same priority) are tried. This actually happens in some library files (I don't know how often).

So far I've talked about the negatives of making instances always available. However, I've also had experiences where type class inference failed until I opened an "extra" namespace. That is pretty confusing.

**Comment by fpvandoorn** [comment] 2015-06-18 04:05
> The need of this particular device attests to the semantic issue that I argued in my last post.

This device exists for all metaclasses, also for coercions. See section 8.8 in the tutorial.

**Comment by leodemoura** [comment] 2015-06-18 04:08
Here is a list of reasons to keep the current approach.

1- It is a uniform approach. All metadata in Lean is handled in the same way. 

2- Different sets of instances may work correctly in isolation, but may produce non-termination and/or poor performance when put together. 

3- If a set of instances is harmless, we can define it at the top-level. 

4- The command `open [classes] <namespace>` is _not_ type class specific. We can use it for any kind of metadata. Example `open [coercions] <namespace>`. We can also "open" only the declarations `open [declarations] <namespace>`.

5- The `export` command allows us to move instances to different namespaces or to the top-level.
Here is an example.

``` lean
namespace foo
... define many instances
end foo
export [classes] foo -- all classes/instances from the namespace foo are copied to the top-level.
```

I don't think we need a `global attribute` command. We can use `attribute` in the top-level, or use the `export` command to move many instance to the top-level.

**Comment by leodemoura** [comment] 2015-06-18 04:27
Floris, the namespaces can also be used to create "custom configurations/solutions". 
For example, it may mark some theorems as rewrite rules, mark some definitions as irreducible, mark another set of constants as user-defined eliminators, etc.
We can have a namespace for domain `X`. Then whenever we want to solve a problem from domain `X`, we can just say `open X`, and the environment is configured with the annotations that are known to work well in this domain.

Even `[refl]` we may want to hide sometimes. For example, the rewrite tactic always try to close the goal by applying reflexivity. We may block this behavior by controlling the `[refl]` annotation.
The `[refl]`, `[trans]` and `[symm]` annotations are also going to be used by the simplifier, and the future `blast` tactic. They only assume that `R` is an equivalence relation if it is annotated with `[refl]`, `[trans]` and `[symm]`. This may be quite important for `blast` since it keeps computing equivalence classes of terms for every relation `R` that is an equivalence. So, the user may want to block that.

If the user always want a set of annotations in the top-level, then they can use `export`.
The `default.lean` is a good place for using this command.

**Comment by htzh** [comment] 2015-06-18 04:49
I agree `export` is a good enough work around. I assume it exports all instances from a namespace regardless of file origin based on your comment about putting it in `default.lean`.

**Comment by leodemoura** [comment] 2015-06-18 04:49
> I assume it exports all instances from a namespace regardless of file origin based on your comment about putting it in default.lean.

Correct.

**Closed as completed** 2015-06-18 06:37 UTC
