### ISSUE TITLE
generalize ignores that namespaces are open

### ISSUE THREAD

**Issue by javra** [leanprover/lean3#421] opened 2015-02-02 22:46 UTC
The `generalize` tactic seems to ignore openness of namespaces, one always has to give the complete unshortened identifier.

Furthermore, all generalized variables are called `x` in the resulting pi type (at least if they're not variables themselves but real subterms).

**Comment by leodemoura** [comment] 2015-02-02 22:56
@javra Please could you provide a self-contained example describing the issue?
The ideal example is a small .lean file that does not depend on any file that is not part of the Lean libraries.
Ideally, the example should contain comments describing exactly 
- features missing
- syntax you want to use
- what you expect as the output
- etc

**Comment by javra** [comment] 2015-02-02 23:15
(all in HoTT mode)
Second point:

```
open eq

definition some_def {A : Type} (a : A) : a = a := refl a
definition some_def2 {A : Type} (a : A) : a = a := refl a

definition foo {A : Type} (a b c : A) (p : a = a) : p = some_def a ⬝ some_def2 a :=
begin
  generalize (some_def a), generalize (some_def2 a),
end
```

I would propose that the two variables both called `x` have different names.

**Comment by leodemoura** [comment] 2015-02-02 23:27
@javra Thanks for posting the example.

However, the following is still not clear to me.

> The generalize tactic seems to ignore openness of namespaces, one always has to give the complete unshortened identifier.

I didn't manage to reproduce this problem. The following works:

```
open eq

namespace foo
  definition some_def {A : Type} (a : A) : a = a := refl a
  definition some_def2 {A : Type} (a : A) : a = a := refl a
end foo

open foo

definition foo {A : Type} (a b c : A) (p : a = a) : p = some_def a ⬝ some_def2 a :=
begin
  generalize (some_def a), generalize (some_def2 a),
end
```

**Comment by javra** [comment] 2015-02-02 23:28
I'm just trying to figure it out. Maybe it needs to be in separate files to fail...

**Comment by leodemoura** [comment] 2015-04-30 19:01
We can now provide a name in the `generalize` tactic.
Example: 

``` lean
    generalize some_def a  as  d1,
    generalize some_def2 a as d2
```

I'm closing this issue since we cannot reproduce it.
If you find a problem, please post it here.

**Closed as completed by leodemoura** 2015-04-30 19:01 UTC
