### ISSUE TITLE
Meta program that traverses product expressions fails

### ISSUE THREAD

**Issue by kendroe** [leanprover/lean3#1963] opened 2018-07-29 19:01 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

A simple meta program to simplify a product expression fails.  The program generates no errors.

### Steps to Reproduce

Try the following program:

meta def simplifyProd : expr → expr
| (expr.app
    (expr.app
      (expr.app `(prod.fst) tt1a)
      tt1b)
     (expr.app
        (expr.app
          (expr.app
            (expr.app `(prod.mk) tt1) tt2) a) b)) := a
| (expr.app a b) := expr.app (simplifyProd a) (simplifyProd b)
| (expr.lam v b t e) := expr.lam v b (simplifyProd t) (simplifyProd e)
| (expr.pi v b t e) := expr.pi v b (simplifyProd t) (simplifyProd e)
| x := x

theorem testit (f:ℕ) (s:ℕ) :
    (f,s).fst=f :=
begin
   do {
       t ← target,
       trace "Start",
       trace t.to_raw_fmt,
       tq ← some (simplifyProd t),
       trace tq.to_raw_fmt,
       change tq
   },
   refl
end

**Expected behavior:** [What you expect to happen]

tq should have the expression "f=f"

**Actual behavior:** [What actually happens]

tq gets the expression (f,s).fs=f

**Reproduces how often:** [What percentage of the time does it reproduce?]

always
### Versions

Lean 3.4.1

**Comment by cipher1024** [comment] 2018-07-30 15:53
Using `dsimp` should get rid of those projections for you.

**Comment by avigad** [comment] 2018-07-30 16:36
@kendroe The right place for questions like is Zulip,  https://leanprover.zulipchat.com/.

There are various bugs in your code:
- you need to quote the constants `prod.fst` and `prod.mk`
- you don't want to use `some` (it dropped you into the `option` monad)
- the parentheses in your first case were associated the wrong way.

The modification below works.

```lean
open tactic

meta def simplifyProd : expr → expr
| `(prod.fst (prod.mk %%a %%b)) := a
| (expr.app a b) := expr.app (simplifyProd a) (simplifyProd b)
| (expr.lam v b t e) := expr.lam v b (simplifyProd t) (simplifyProd e)
| (expr.pi v b t e) := expr.pi v b (simplifyProd t) (simplifyProd e)
| x := x

theorem testit (f:ℕ) (s:ℕ) :
(f,s).fst=f :=
begin
do {
t ← target,
trace "Start",
trace t,
let tq := (simplifyProd t),
trace tq,
change tq
},
refl
end
```

**Comment by leodemoura** [comment] 2018-07-30 17:31
@avigad @cipher1024 Thanks. 

Since this is not a bug, I am closing this issue.

**Closed as completed by leodemoura** 2018-07-30 17:31 UTC
