### ISSUE TITLE
rewrite tactic in HoTT library

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#433] opened 2015-02-13 04:17 UTC
Jakob and I noticed that the rewrite tactic tends to fail a lot in the HoTT library. I thought that the higher order unification failed to find the correct solution, but maybe there is something going on with universe levels (see below). 

To give some examples where rewrite works in Coq, but fails in Lean, here are some rewrite tactics in the Coq-HoTT library:
https://github.com/HoTT/HoTT/blob/master/theories/Types/Forall.v#L153-156
Here is a working port of it, using `apply (transport ...)` (with explicit type family of the transport) instead of `rewrite`:
https://github.com/fpvandoorn/lean/blob/rewrite/hott/types/pi.hlean#L109-120
(note: [transport_V](https://github.com/fpvandoorn/lean/blob/rewrite/hott/types/pi.hlean#L94-95) is just `transport` along the inverse path, so that `rewrite foo` corresponds to `apply (transport_V _ foo)`)
(note 2: this repository is just the blessed repository where only `types/pi.hlean` has been modified)

Below each line are two commented out tactics, the first one is the rewrite tactic as Coq used it, and the second is the rewrite tactic with all arguments supplied to the theorem. 

All these rewrite tactics fail.

All of them give the same error message "tactic failed", except `rewrite (adj f0 a'),` which gives the very weird (but hopefully interesting) error message:

```
type mismatch at application
  eq
term
  function.compose f0 f0 ⁻¹ (f0 a') = function.id (f0 a')
has type
  Type.{l}
but is expected to have type
  Type.{k}
```

I really hope these rewrites all fail because there is some minor universe error in the rewrite tactic, instead of a failing higher-order unification.

**Comment by leodemoura** [comment] 2015-02-13 18:26
@fpvandoorn I found and fixed one bug in the HoTT mode.
https://github.com/leanprover/lean/commit/98960cbeda9aadce25e7cf9731d11691582a7e63

Now, we can use `rewrite (adj f0)`, instead of `apply (transport_V _ (adj f0 a'))`. 

The rewrite tactic is based on higher-order matching. This is why `rewrite adj`  does not work. In this case, the left-hand-side would be something like `(retr ?f (?f ?x))`. 
This is not a higher-order pattern. In a higher-order-pattern, a metavariable cannot be the argument of another metavariable (e.g. `?f ?x`).

BTW, we can also provide our own patterns to the rewrite tactic

```
     rewrite {retr f0 _}adj
```

I did not close the issue because the other `rewrite` tactics in your file do not work. 
Do you expect all of them to work?

**Comment by leodemoura** [comment] 2015-02-13 19:19
@fpvandoorn `rewrite -transport_compose` also does not work because the left-hand-side is not a higher-order pattern. It has the form

```
@eq.transport ?B ?P (?f ?x) (?f ?y) (@ap ?A ?B ?f ?x ?y ?p) ?z
```

The problem are the subterms `?f ?x` and `?f ?y`.
I managed to workaround the issue by providing my own pattern:

```
  rewrite -{eq.transport _ (ap _ _) _}transport_compose,
```

Now, I'm wondering if we should "cleanup" the patterns before we try to match.
For example, 

```
@eq.transport ?B ?P (?f ?x) (?f ?y) (@ap ?A ?B ?f ?x ?y ?p) ?z
```

does not qualify as a pattern. Then, we replace the offending terms by fresh metavariables.

```
@eq.transport ?B ?P ?M1 ?M2 (@ap ?A ?B ?f ?x ?y ?p) ?z
```

BTW, matching is just a quick/efficient way to locate places where rewriting should be considered.
After we locate them, higher-order unification is used anyway.

**Closed as completed** 2015-02-13 20:41 UTC

**Comment by leodemoura** [comment] 2015-02-13 20:43
@fpvandoorn I implemented the trick I described in the previous comment.
I think the rewrite tactic is more convenient to use now.
Take a look at:
https://github.com/leanprover/lean/blob/5cbdd77ad039e3ab1ff06dafca4b94589d3aabe3/tests/lean/hott/433.hlean#L99-L120

**Comment by fpvandoorn** [comment] 2015-02-16 23:09
This looks very nice! 

In the test I'm confused about the comment
`-- retr cannot be used as rewrite rule, the resulting type is not an equality`
The conclusion of `retr` is `function.compose f f ⁻¹ ∼ function.id` which can be unfolded to `forall x, function.compose f f ⁻¹ x = function.id x`. Does the current rewrite tactic not unfold definitions in the theorem with which you want to rewrite? I think that would be nice to have.

**Comment by leodemoura** [comment] 2015-02-16 23:33
My mistake. 
`∼` is marked as reducible. So, it will be unfolded by the `rewrite` tactic.
If we use

```
rewrite (retr (f1 _) _)
```

Lean uses the following pattern:

```
@function.compose (B' ?M_1) (B (f0 ?M_1)) (B' ?M_1) (f1 ?M_1)
                  (@inv (B (f0 ?M_1)) (B' ?M_1) (f1 ?M_1) ?M_2) ?M_3
```

The rewrite tactic works in the following way:
1- If a pattern is provided, then it is used. If it is not provided, then the left-hand-side of the of the equality provided is used as a pattern.
2- Then, the goal (and/or hypotheses if `at` is used) is traversed, and Lean tries to match the pattern against subterms. The matching procedure is very restrictive: only constants marked as reducible are unfolded; projections are never unfolded; terms marked as implicit instances (the `[a : A]` notation) are "ignored"; the matcher only supports higher-order patterns. 
3- If a subterm `t` matches the pattern, then Lean will try to use higher-order unification (and type class synthesis) to synthesize the missing arguments of the lemma provided by the user.
The unification step is also conservative: only constants marked as reducible are unfolded (projections included).
4- If the previous step is successful, then all occurrences of the subterm `t` are replaced (unless the user provides a subset of the occurrences), and the rewrite step terminates. If the unification step fails the search continues. 

We should view the matching step as a heuristic to select potential places where the rewriting step can be applied.

**Comment by leodemoura** [comment] 2015-02-16 23:44
Here is the real reason `rewrite (retr (f1 _) _)` fails.
The problem is that the `function.compose` reducibility attribute is "part of" the `function` namespace.
So, if we don't open `function`, `function.compose` is not really reducible. 
If we execute

```
open function
```

then `rewrite (retr (f1 _) _)` succeeds.

Here is another possibility:
We define `function.compose` in the top-level as

```
definition function.compose [reducible] (f : B → C) (g : A → B) : A → C :=
λx, f (g x)
```

Then, it will always be `reducible`. What do you think?

**Comment by fpvandoorn** [comment] 2015-02-17 02:35
The matching sounds good. It's good that it's more restrictive than full higher order unification, because that tends to make the search space too big.

I think it's good to make `function.compose` (and also `function.id`) always reducible.
