### ISSUE TITLE
file is corrupted, please regenerate the file from sources

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#925] opened 2015-12-11 23:59 UTC
I get this error message quite often when building Lean while also working on some Lean file in Emacs. I now manage to almost-consistently reproduce it (5 out of 7 times I tried), using the steps below. Note: before I did this, I executed `ninja clean && ninja clean-olean && ninja` and it compiled fine, so compiling itself is not the problem. Steps to reproduce (these are for HoTT, but I can also reproduce it in the standard library):

(0) close all open `hlean` files in Emacs.
(1) In the command line, navigate to the `hott/` folder and execute `git clean -Xf && linja`
(2) Quickly (while it is compiling) open `hott/algebra/category/functor/adjoint.hlean` in an Emacs buffer and press space to make sure Flycheck is running.
(3) Now there is a high chance you will get an error like the following in the command line

```
failed to import '.../projects/lean/hott/...', file is corrupted, 
please regenerate the file from sources
```

Note: I can also reproduce it when replacing step (1) by
(1') In the command line, navigate to the `build/whatever` folder and execute `ninja clean-hott-lib && ninja`.

Once, I didn't get the above error message, but I got the error message:

```
home/floris/projects/lean/hott/algebra/category/limits/adjoint.hlean:9:0: error: file 
'/home/floris/projects/lean/hott/algebra/category/functor/adjoint.olean' 
has been corrupted, unknown object
```

(two notes: in this error message, the paths are different, and the file I opened in step 2 was indeed `functor/adjoint.hlean`)

Conclusion: Flycheck is interfering with the build.

**Comment by soonhokong** [comment] 2015-12-12 13:19
@fpvandoorn, I'll try to reproduce it today.

**Comment by leodemoura** [comment] 2015-12-12 16:16
@soonhokong I also have this problem all the time.
The issue is that there are two different builds running simultaneously: the command line one; and the flycheck one.
I didn't report it because this is an expected limitation. We would have similar problems if we try to build any project, and use two different simultaneous ninja/make commands.
I don't see any simple and efficient solution. I think the right solution is to implement the "compilation server" we discussed a long time ago.

The "compilation server" would be an executable that controls all building process for Lean, it would replace `linja`, and the `lean-server`. It would track dependencies, perform incremental builds, and retrieval of information (type, auto-completion, etc). I don't know if you remember, but I tried to start it some time ago, and you asked me about it. 

One hackish solution is to use separate set of files for flycheck and command line linja. I think this is far from ideal. It is more overhead, and it doesn't completely solve the problem. The user may still start `linja` twice from the command line in two different directories that share dependencies.

Here is another hackish 'solution', in the directory containing the `.project` file, we create a `.busy` file whenever we start a build. Moreover, we check the existence of this file whenever we try to start a build process. If it exists, the new build waits until it is deleted. Potential problems, the `.busy` file accidentally stays there, and we can't build anything else. Well, the `clean` could delete it. Notice this is not a robust solution.

I think the short term solution is: "tell users they have to wait command line `linja` to finish before they continue editing `.lean` files on `emacs`" This is what I do, when I run `ninja standard_lib` in the command line.

**Comment by Kha** [comment] 2015-12-12 17:29
@leodemoura 

> Potential problems, the .busy file accidentally stays there, and we can't build anything else.

The robustness of that solution could be increased by storing the PID of the locking process in the `.busy` file.
While a compilation server sounds great for Isabelle/PIDE-like interaction, I actually would have expected two separate servers to be spawned in the use case described above (one from the build, one from emacs), ie there not to be a single system-global server.

**Comment by leodemoura** [comment] 2015-12-12 17:48
> The robustness of that solution could be increased by storing the PID of the locking process in the .busy file.

Great idea.
Do you see other problems with the `.busy` file approach?

**Comment by leodemoura** [comment] 2015-12-12 18:03
> I actually would have expected two separate servers to be spawned in the use case described above (one from the build, one from emacs), ie there not to be a single system-global server.

I was planning to have a single global one, but you are right, unless we install a daemon, we would get two different process, and the same problem again.

**Comment by Kha** [comment] 2015-12-12 18:09
> Do you see other problems with the .busy file approach?

It should be fine, I think it is a quite standard UNIX approach. E.g. vim uses it to prevent simultaneous edits to its per-file metadata and gives a nice warning dialog:

```
Found a swap file by the name "~/.vim/swap/.vimrc.swp"                                                                                                                           
          owned by: sebastian   dated: Sat Dec 12 18:56:43 2015                                                                                                                  
         file name: ~sebastian/.vimrc                                                                                                                                            
          modified: no                                                                                                                                                           
        process ID: 26172 (still running)
```

Actually, wouldn't a per-file (.lean/.olean) lock be sufficient for Lean, too?

**Comment by leodemoura** [comment] 2015-12-12 18:41
> Actually, wouldn't a per-file (.lean/.olean) lock be sufficient for Lean, too?

I agree, we could use a `.busy` file for each `.lean` file. It would be a "lock" for the lean generated files (`.olean`, `.ilean` and `.clean`). 
Is the following a good solution?
- Whenever we invoke Lean to compile a `.lean` file, it would first check if the associated `.busy` file exists.
- If the file exists, then check if the process ID stored in it is still alive, if it is not, then ignore the file.
- If the process ID is still active, then wait and keep checking, if the process still exists after `k` secs, generate an error message.
- Otherwise, create the `.busy` file and store the Lean own process ID in it, and continue the compilation process.
- When done, erase the `.busy` file.

Issue:
- How do we prevent a race condition when creating the `.busy` file. That is, two different processes try to simultaneously create the `.busy` file.  I'm unaware of a platform independent solution.
  I think we have to address this issue per platform.

**Comment by Kha** [comment] 2015-12-12 23:02
> How do we prevent a race condition when creating the .busy file. That is, two different processes try to simultaneously create the .busy file. I'm unaware of a platform independent solution.

Ah, I didn't know whether the stdlib had support for that. Well, if we have to resort to a platform-dependent solution, we may as well use native file locking methods on the output file, removing the need for both lock files and PID checking. `flock` seems to have some quirks, but since we don't need a 100% bullet-proof solution, it should be fine I think.

**Comment by leodemoura** [comment] 2015-12-13 05:39
I added a simple locking mechanism using `flock`. The Windows version is still missing. Some people claim that the `flock` API is supported in MSYS, and others claim it is not. I will check on Monday.
I tested on Linux and OSX, and it seems to work.
Without the lock, I managed to reproduce  Floris' issue in the first try.
With the lock, I tried 3 times, and had no problems.

@fpvandoorn could you test on your machine?

**Comment by fpvandoorn** [comment] 2015-12-13 05:44
Great! I will test it tomorrow.

**Comment by leodemoura** [comment] 2015-12-13 05:48
@Kha I used a `f.olean.lock` file to "lock" `f.olean` because the `flock` API is based on the C low level file descriptions, and all Lean IO operations are based on the high level C++ iostream library. 
It was also easier to adapt the cooking recipes people have on the internet.

**Comment by Kha** [comment] 2015-12-13 12:30
@leodemoura That makes sense. The code looks very reasonable to me.

**Comment by leodemoura** [comment] 2015-12-14 18:28
I've added support for Windows: https://github.com/leanprover/lean/commit/31c9a76777bf6d24c923b0383a754461bc597e10

I'm closing this issue, I believe the problem has been fixed in all major platforms (Win, OSX and Linux)
We can reopen if we find the problem again.

**Comment by soonhokong** [comment] 2015-12-15 15:32
Dear @leodemoura,

I just noticed that the recent locking feature creates a problem if a user installs Lean from PPA. The problem is that Lean library is installed at `/usr/lib/lean/library` and lean is trying to create a `.lock` file such as `/usr/lib/lean/library/init/default.olean` but fails to do so because the user doesn't have a write permission on the directory.

Here is a minimal reproduce steps:
- Install Lean via PPA
- Create a test file `test.lean` which only contains "import standard"
- Run `lean test.lean`. It will generate the following error

```
test.lean:1:0: error: failed to lock file '/usr/lib/lean/library/init/default.olean'
```

**Comment by leodemoura** [comment] 2015-12-15 17:01
@soonhokong :-(
The solution is to save them in the tmp directory.
I will investigate how to create the tmp files in the different platforms.

**Comment by leodemoura** [comment] 2015-12-15 17:15
@soonhokong What do you think of the following solution?
1- If `TMP` environment variable is defined, then assume it is the the temp folder (as far as I know, this environment variable is defined in Windows).
2- If `TMP` is not defined, then use `/tmp`. (as far as I know, all Linux and OSX distributions have a `/tmp` folder for temporary files).

We can also sign an error if we fail to create the .lock file, and tell that the environment variable `TMP` is used to decide where we create the file.

**Comment by soonhokong** [comment] 2015-12-15 17:15
My feeling is that saving `.lock` files in the tmp directory is harder since we need to preserve the directory structure to distinguish the files with same name (or the two lean processes share the same naming convention to resolve this issue?).

Can we do the following hack? If lean has no permission to create a `.lock` file, then we assume that it's safe to load the file without locking it because it's read-only (there is no read/write conflict)? I understand that it requires us to figure out platform-dependent ways of checking permissions..

**Comment by leodemoura** [comment] 2015-12-15 17:16
> My feeling is that saving .lock files in the tmp directory is harder since we need to preserve the directory structure to distinguish the files with same name (or the two lean processes share the same naming convention to resolve this issue?).

I forgot that :-(

**Comment by leodemoura** [comment] 2015-12-15 17:20
> Can we do the following hack? If lean has no permission to create a .lock file, then we assume that it's safe to load the file without hack because it's read-only (there is no read/write conflict)? I understand that it requires us to figure out platform-dependent ways of checking permissions.

Good point. 
I think we may be able to check that using the error code from a failed `open`. I will check.

**Comment by soonhokong** [comment] 2015-12-15 17:20
> I understand that it requires us to figure out platform-dependent ways of checking permissions..

A possible heuristic to check a permission is 1) check there is no `a.olean.lock` file, 2) create `a.olean.lock` while ignoring any exception/error from this operation, 3) check if `a.olean.lock` is created.

If 3) gives yes, we do have a permission. If 3) gives no, something is wrong and consider it as having no permission... I guess this is (relatively) easy option to implement..

**Comment by leodemoura** [comment] 2015-12-15 17:21
@soonhokong I will try your suggestion

**Comment by soonhokong** [comment] 2015-12-15 17:21
> I think we may be able to check that using the error code from a failed open. I will check.

I see. For sure, checking the error code is the right way.. I was just thinking about an easiest workaround.

**Comment by leodemoura** [comment] 2015-12-15 18:48
I think it is fixed.

**Closed as completed by leodemoura** 2015-12-15 18:48 UTC

**Comment by soonhokong** [comment] 2015-12-15 19:53
@leodemoura, thank you! [PPA](https://launchpad.net/~leanprover/+archive/ubuntu/lean) is updated.
