### ISSUE TITLE
notation both infix and postfix

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#712] opened 2015-06-26 16:42 UTC
Small issue with using notation both as infix and postfix:

``` lean
reserve infix `~~~`:50
local postfix `~~~` :(max+10) := eq -- fails

reserve postfix `~~~`:(max+10)
local postfix ~~~ := eq -- succeeds


-- and maybe we can also accept this? 
-- (only if the binding power matches the binding power in the reserve command)
local infix `~~~`:50 := eq -- fails
```

I had to make a change in `pnat` because of this: https://github.com/leanprover/lean/commit/124c9d3d8ae8fede44266ead3bdc808762fa485f#diff-340769d138a268f8903fc096d67effb0

**Comment by leodemoura** [comment] 2015-06-29 16:28
This is a questionable feature. 

The following command is supposed to fail

``` lean
reserve infix `~~~`:50
local postfix `~~~` :(max+10) := eq
```

because the `postfix` command is changing the binding power of a reserved notation.
The `infix` and `postfix` command both set the "left binding power" of the give token.
So, the local notation above will change how the reserved notation is parsed.

The main point of the reserved notation is to prevent us from setting binding powers in different files, and making sure they match.

``` lean
-- and maybe we can also accept this? 
-- (only if the binding power matches the binding power in the reserve command)
local infix `~~~`:50 := eq -- fails
```

**Comment by leodemoura** [comment] 2015-06-29 16:51
I'm closing this issue since this is the intended behavior.
Feel free to reopen it.

**Comment by fpvandoorn** [comment] 2015-07-06 19:17
Ok, that makes sense. So to recap:
- we can use a token both for infix and prefix notation (such as `-`)
- we cannot make a token both for infix and postfix notation (if they have different binding power).

Right?

So can you confirm that [these two lines](https://github.com/leanprover/lean/blob/master/library/data/pnat.lean#L25-26) can break other files when the `~` is also used as infix notation? In that case, I will change the postfix notation used there.

**Comment by leodemoura** [comment] 2015-07-07 01:30
> we can use a token both for infix and prefix notation (such as -)
> we cannot make a token both for infix and postfix notation (if they have different binding power).
> Right?

Correct. 

> So can you confirm that these two lines can break other files when the ~ is also used as infix notation? In that case, I will change the postfix notation used there.

Yes, it will create problems. 
The problem is that the `reserve` notation is not local.
This is a good example that shows that we should allow `local` notation to override reserved notation.

**Comment by leodemoura** [comment] 2015-07-07 01:31
I'm reopening the issue. We should allow local notation to change the binding power defined by reserved.

**Closed as completed** 2015-07-08 01:04 UTC
