### ISSUE TITLE
Potential room for improvement in eqn-compiler error message

### ISSUE THREAD

**Issue by dselsam** [leanprover/lean3#1258] opened 2016-12-19 15:23 UTC
```Lean
constant P : list ℕ → list ℕ → Prop
lemma foo (xs : list ℕ) : Π (ns : list ℕ), P xs ns
| []      := sorry
| (n::ns) := begin cases xs, exact sorry, exact sorry end
```
yields
```
error: support for well-founded recursion has not been implemented yet, 
use 'set_option trace.eqn_compiler true' for additional information
```
with trace
```
[eqn_compiler] compiling
def foo : ∀ (ns : list ℕ), P xs ns
| list.nil := sorry
| (n :: ns) := list.cases_on xs (λ (foo : ∀ (ns : list ℕ), P list.nil ns), sorry)
  (λ (a : ℕ) (a_1 : list ℕ) (foo : ∀ (ns : list ℕ), P (a :: a_1) ns), sorry)
  foo
[eqn_compiler] recursive: 1
[eqn_compiler] nested recursion: 0
[eqn_compiler.structural_rec] using structural recursion on argument #1 for 'foo'
[eqn_compiler.structural_rec] 
new function type: ∀ (ns : list ℕ), list.below ns → P xs ns
motive type:       list ℕ → Prop
[eqn_compiler.structural_rec] unexpected occurrence of recursive function: foo
[eqn_compiler.structural_rec] failed to compile equations/match using structural 
recursion, when creating new set of equations
```
The `cases xs` tactic is the problematic one, and I assume that one is not allowed to apply a recursor to a parameter (that appears to the left of the `:`). This is very low priority, but if it were possible/easy to detect this case earlier, a message that explains the problem would be helpful. I encountered this issue as part of a much bigger proof and it took me a while to figure out what the problem was.

**Comment by leodemoura** [comment] 2016-12-19 17:40
The problem is that the `cases` tactic reverted the auxiliary local decl `foo : ∀ (ns : list.{1} nat), P xs ns` used by the equation compiler, and produced the term `list.cases_on ... foo`. Note that `foo` was reverted because it depends on `xs`. 
The subterm `foo` introduced by `cases` is not applied to a list object. Thus, it cannot be eliminated by the equation compiler using structural or well-founded recursion. A possible workaround is to use `clear foo` before the `cases xs` tactic.
I'm not sure what is a good error message here. We can tell the user that the recursive equations are invalid because there is a non-applied `foo` on the right-hand-side. However, it is still confusing since the user did not write any `foo`. It was produced behind the scenes by the `cases` tactic.
We may also modify the `revert` tactic and prevent it from reverting auxiliary declaration introduced by the equation compiler, and prevent this instance of the problem from happening.

**Comment by leodemoura** [comment] 2016-12-20 20:51
The commit above prevents the weird error message. So, I'm closing this issue.

**Closed as completed by leodemoura** 2016-12-20 20:51 UTC

**Comment by avigad** [comment] 2016-12-23 01:00
This fixed all the problems in `library_dev`, both the broken recursive calls and the problem with `let` definitions. Thanks.
