### ISSUE TITLE
Lean unstable

### ISSUE THREAD

**Issue by htzh** [leanprover/lean3#593] opened 2015-05-10 02:31 UTC
The problem seems to have started with my recent changes to https://github.com/htzh/leanproved/blob/master/group_theory/hom.lean. Editing the file in emacs lean mode causes lean to generate uncaught exceptions after almost every key stroke. Editing the subgroup.lean file does not seem to have any problem.

I am still on a two days old version of Lean due to issue #591. My build was without tcmalloc and without -DBOOST using: `cmake -D CMAKE_CXX_COMPILER=g++.exe -DCMAKE_INSTALL_PREFIX=/usr/local/ -G Ninja ../src`. I am mostly up-to-date with regard to MSYS2

**Comment by leodemoura** [comment] 2015-05-10 04:58
I cloned your repository and have been editing your files for several minutes without problems.
Recent changes modified the format of .olean files. So, this may be the source of the problem.
The tool `linja` is supposed to detect when the `lean` binary has been updated and recompile everything.
However, there is a problem with this feature (see issue #575). It is not clear to me where the problem is. 
@soonhokong is investigating the problem.
So, in the meantime, please try to clean all object files in your project directory. You can use the following command:

```
linja clean
```

The `linja` script is located at `<path-to-lean>/bin/linja`. It is in the same directory of the `lean` binary.

**Comment by htzh** [comment] 2015-05-10 05:34
Unfortunately that didn't work for me. The message from the VS JIT debugger says:

```
Unhandled exception at 0x00432EAD in lean.exe: 0xC0000005: Access violation reading location 0x00000020.
```

Not sure if that means anything.

**Comment by htzh** [comment] 2015-05-10 06:00
I rolled back my hom.lean to e881d37abefaa6370276a3b9dabffa7522a5f606 and Lean stopped crashing. So at least on my part it is triggered by the changes in hom.leam. Due to the build issue my lean is on version e2c1dc92a8f85afd2470e9032d50b1b5b54b5776

**Comment by leodemoura** [comment] 2015-05-10 06:05
I'm puzzled. I have a machine with msys2 in my office. I will try to reproduce the behavior on Monday.

**Comment by htzh** [comment] 2015-05-10 06:11
I separated out the section where I thought was problematic. I used to have a class instantiated and included later in the section. I wasn't sure that was legal but Lean accepted it. Now I put it in the beginning of its own section and the crashing seemed to have stopped. It could be entirely a coincidence though.

**Comment by htzh** [comment] 2015-05-10 06:14
Change is also on github.
```
diff --git a/group_theory/hom.lean b/group_theory/hom.lean
index 82aa5e0..d88d22c 100644
--- a/group_theory/hom.lean
+++ b/group_theory/hom.lean
@@ -52,6 +52,15 @@ theorem hom_map_mul_closed (Hom : is_hom f) (H : set A) : mul_closed_on H → mu
         ... = b1 * f a2 : {and.right Pa1}
         ... = b1 * b2 : {and.right Pa2},
         in_image Pa1a2 Pb1b2
+end^M
+section^M
+variables {A B : Type}^M
+variable [s1 : group A]^M
+variable [s2 : group B]^M
+include s1^M
+include s2^M
+variable f : A → B^M
+variable Hom : is_hom f^M

 variable {H : set A}
 variable [is_subgH : is_subgroup H]

```

**Comment by htzh** [comment] 2015-05-10 06:23
Disregard the last two messages. It still crashes but maybe less severely. I will wait for the build issue to resolve and check out the latest version of Lean and see if that helps.

**Comment by soonhokong** [comment] 2015-05-10 11:02
@htzh, could you try the latest build? I just pushed a fix for #591. I still need to figure out the reason why this patch fixes the problem but I confirmed that the fix itself is harmless so it's safe to be pushed to the blessed.

Let me check #575 this evening. I also only have my Windows machine at the lab. To avoid a problem like #575, I do the following:

``` bash
cd lean/library
git -fxd
cd ../hott
git -fxd
```

The above steps clean up `lean/library` directory and `lean/hott` directory. After running them, go to your build directory and build it again (just `make` or `ninja`). I'm not sure that this helps your problem but I can confirm that this clears up any issues with #575.

**Comment by htzh** [comment] 2015-05-10 15:37
I can confirm that the build goes through fine now. Thanks Soonho! I was
still able to crash Lean but the impression is that it is less frequent
now. I will report if I see a pattern. What does everyone use here? Linux?
I have a Linux vbox. I am a bit leery of running GUI out of it. I can try
emacs out in terminal mode and see how that goes.

**Comment by htzh** [comment] 2015-05-10 16:57
I tried to build on my ArchLinux vbox. The build went smoothly. But there is apparently something wrong with the install script:

```
CMake Error at shell/cmake_install.cmake:36 (file):
  file INSTALL cannot find
  "/home/haitao/lean/build/shell/CMakeFiles/CMakeRelink.dir/lean".
Call Stack (most recent call first):
  cmake_install.cmake:90 (include)


FAILED: cd /home/haitao/lean/build && /usr/bin/cmake -P cmake_install.cmake
ninja: build stopped: subcommand failed.
```

I can use the non-installed directory for now.

**Comment by leodemoura** [comment] 2015-05-10 18:20
@htzh Could you provide the sequence of commands you used?

> What does everyone use here? Linux?

As far as I know, most of us use: Ubuntu, Kubuntu or OSX

**Comment by htzh** [comment] 2015-05-10 18:23
```
 515  git clone https://github.com/leanprover/lean.git
  516  ls
  517  cd lean/
  518  ls
  519  cd src
  520  cd ..
  521  mkdir build
  522  ls
  523  which ninja
  524  sudo pacman -S ninja
  525  cd build/
  526  cmake -D CMAKE_CXX_COMPILER=g++.exe -DCMAKE_INSTALL_PREFIX=/usr/local/ -G Ninja ../src
  527  cmake -D CMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=/usr/local/ -G Ninja ../src
  528  pacman -Ss tcmalloc
  529  pacman -S gperftools
  530  sudo pacman -S gperftools
  531  cmake -D CMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=/usr/local/ -G Ninja ../src
  532  ls /usr/local/bin
  533  ls
  534  ninja install
  535  sudo ninja install
  536  which lean
  537  ninja
  538  sudo ninja install
  539  ls ../bin/
```

**Comment by leodemoura** [comment] 2015-05-10 18:47
@soonhokong I didn't manage to reproduce the error on Ubuntu... Any suggestions?

**Comment by soonhokong** [comment] 2015-05-10 18:49
@htzh, could you let us know 1) the version of Arch Linux that you're using, 2) cmake version? I can try to reproduce the problem in a fresh Arch Linux VM this evening.

I remember a student of @avigad is adding Lean to the Arch Linux package repository. Is it up-do-date?

**Comment by htzh** [comment] 2015-05-10 19:50
I am running emacs in a telnet (puTTY) into my vbox and now it is running fine. No crashing Lean. My MSYS2 version of Lean is pretty unusable right now on hom.lean. ~~Amazingly emacs still works well in the terminal mode.~~ However I am not very used to the terminal mode so I hope to get back to the gui soon when the Windows build is stable again.

@soonhokong I just updated vbox and archlinux (with pacman -Syu) so should be current.  cmake is at:

```
extra/cmake 3.2.2-1 [installed]
```

The install issue for Arch is very low priority for me. I am happy to run from the ~/lean/bin directory.

**Comment by htzh** [comment] 2015-05-10 21:20
I am able to hobble along in a new section of hom.lean using my Windows emacs/lean and so far crash has not happened. So it appears it was somehow related to a particular section (the first section) of the file.

**Comment by soonhokong** [comment] 2015-05-11 03:10
@htzh, I couldn't reproduce the error either. I downloaded an image of Arch Linux VM from [osboxes.org](http://www.osboxes.org/arch-linux/). Then I did the following to install Lean:

``` bash
pacman -S git cmake gcc gmp mpfr lua ninja python
git clone https:github.com/leanprover/lean
cd lean && mkdir build && cd build
cmake -DCMAKE_CXX_COMPILER=c++ -DCMAKE_INSTALL_PREFIX=/usr/local -G Ninja ../src
ninja
sudo ninja install
```

Everything went well. FYI, it's `3.18.6-1-ARCH` and has cmake-3.2.2.

**Comment by htzh** [comment] 2015-05-11 04:00
@soonhokong , thanks for checking it out! I am okay with how it works for now. What I really want to know is if there is a simple way to run emacs in Windows while running Lean in vbox. I have set up a telnet server inside the vbox (only opens internally through vbox's internal network bridge feature). That is how I always used the vbox since its own terminal is no fun to use. Now in emacs we should be starting lean with some start-process cmd. If instead we can start-process a telnet (or anything that connects to a telnet port, which is just tcp) and has it run Lean inside the vbox I could be always using the Linux version of Lean instead of the Msys2 build. Do you think this is doable? Thanks a lot.

**Comment by soonhokong** [comment] 2015-05-11 06:26
> What I really want to know is if there is a simple way to run emacs in Windows while running Lean in vbox.

This is possible, but I don't think it's a good direction. We do have some Windows users and we will have more users, sooner or later. I think a natural direction is to fix the `Unhandled exception` problem so that you and other users can use Lean natively on Windows machines.

I will try to reproduce the problem on my Windows machine tomorrow.

**Comment by leodemoura** [comment] 2015-05-11 17:14
@soonhokong I compiled `lean` using `msys2`. The whole library can be compiled without problems. I also managed to compile @htzh library without problems (using the command line):
![image](https://cloud.githubusercontent.com/assets/2778936/7570575/fb4a67d6-f7c5-11e4-8a8b-9b2fea989ff4.png)

However, when I open Emacs, nothing works. Every keystroke produces an error.
Here is error trace produced by `linja`.
![image](https://cloud.githubusercontent.com/assets/2778936/7570600/293bec14-f7c6-11e4-9652-0e45052fd743.png)

Haito: do you get a similar error message?

**Comment by htzh** [comment] 2015-05-11 17:27
@leodemoura I don't recall seeing the error trace, instead I got a window pop-up that says Lean has crashed and Windows would helpfully offer to start a JIT debugger since I have VS installed. My lean is compiled for release not debug so I couldn't see the symbol table to see what crashed.
The crashing was particular bad at the version of my file that I opened this issue with. I switched to Linux terminal mode for a while then I switched back to windows again. I was able to edit or interact with no crashing in a new third section at the end of file. I think I can still trigger crash if I merge the first two sections by cutting the the following (I just verified that the crash still does happen):

```
end
section
variables {A B : Type}
variable [s1 : group A]
variable [s2 : group B]
include s1
include s2
variable f : A → B
variable Hom : is_hom f

```

**Comment by leodemoura** [comment] 2015-05-11 17:51
I compiled `lean` in release mode too. The error trace (in my previous message) is not produced by Lean, but `linja`. `linja` is a Python script (that invokes `lean`).

I removed the block you suggested, and I did not experience any crash on `lean`.

It seems I'm experiencing a different problem. 

This is a tricky problem, could you please provide additional information?
- Windows version (Vista, 7, 8, 8.1)? (I'm using Windows 8.1)
- 32 or 64 bits system? (I'm using 64 bits).
- g++ version? (I'm using 4.9.1)

I'm also not using `tcmalloc` nor `Boost`.

**Comment by htzh** [comment] 2015-05-11 17:58
I am using Windows 8.1 (auto updated to current). Windows is 64 bit but I use the 32 bit version of msys2/mingw-packages, so g++ is 32 bit generating 32 bit code.

```
$ g++ --version
g++.exe (Rev5, Built by MSYS2 project) 4.9.2
```

**Comment by soonhokong** [comment] 2015-05-11 18:15
@leodemoura, I'll fix the python error this evening.

@htzh, was there any reason not to use 64-bit msys2 packages?

**Comment by htzh** [comment] 2015-05-11 18:21
@soonhokong Not really. Just a hunch that most programs don't benefit much from being 64 bit other than making the image larger and pointers wider than needed. But if you think Lean can benefit from using 64 bit (maybe due to gmp or mpfr) or just for the benefit of having fewer variations it is not a problem to switch. I have both versions installed. It is just a question of which terminal I run in. I have more installed packages in 32 bit version but Lean has very few dependencies so that is not a problem. Do you prefer Python 3 as well?

**Comment by soonhokong** [comment] 2015-05-11 18:27
@htzh, I would try the 64bit packages. Could you test that and let us know what you have?

> Do you prefer Python 3 as well?

It should work on both Python2 and Python3.

**Comment by htzh** [comment] 2015-05-11 23:36
I can build in 64 bit and it runs fine from the command line, but emacs does not work at all like @leodemoura said. Also Python 3 does not work for the build on mingw64, but Python 2 worked.
My error message in emacs says:

```
Suspicious state from syntax checker lean-checker: Checker lean-checker returned non-zero exit code 1, but no errors from output: [1/4] generating dep... \Users\haitao\proj\lean\proved\group_theory\flycheck_subgroup.d
```

**Comment by htzh** [comment] 2015-05-11 23:44
The first python 3 failure came here, and then there are many cascading failures:

```
[353/354] cmd.exe /C "cd /D C:\alt\msys32\home\haitao\lean\hott && C:\alt\msys32\mingw64\bin\python3.4.exe C:/alt/msys32/home/haitao/lean/src/../bin/linja all tags"
[354/354] cmd.exe /C "cd /D C:\alt\msys32\home\haitao\lean\library && C:\alt\msys32\mingw64\bin\python3.4.exe C:/alt/msys32/home/haitao/lean/src/../bin/linja all tags"
FAILED: cmd.exe /C "cd /D C:\alt\msys32\home\haitao\lean\hott && C:\alt\msys32\mingw64\bin\python3.4.exe C:/alt/msys32/home/haitao/lean/src/../bin/linja all tags"
```

This is just FYI as I don't care which Python to use.

**Comment by soonhokong** [comment] 2015-05-12 00:22
@htzh, thanks for the report. It's great to know that the use of 64-bit packages solved the build problem. I'll reproduce and fix the Python problem which @leodemoura originally reported.

**Comment by htzh** [comment] 2015-05-12 00:58
@soonhokong just to be clear the build issue was solved since you fixed issue #591 and now both mingw32 and mingw64 build work (at least with python 2). Linja command line also works fine with both. The problem is when used with Emacs lean is unstable when built using mingw32 and not usable when built with mingw64 as reported.

**Comment by htzh** [comment] 2015-05-12 01:01
@soonhokong sorry I didn't update you on #591 and when this issue started it was not fixed yet.

**Comment by htzh** [comment] 2015-05-12 01:06
@soonhokong I did update the build issue earlier in this thread in response to your question https://github.com/leanprover/lean/issues/593#issuecomment-100656860 but I am sorry if you missed it. I should have cross-posted to #591.

**Comment by soonhokong** [comment] 2015-05-12 14:46
@htzh, I think I got confused. So you don't have any problem in building/running Lean and the only problem is using it inside of emacs, right?

@htzh and @leodemoura, I can't reproduce the problem on my Windows machine. I can edit @htzh's `hom.lean` file on my emacs without a problem. Here are the versions of the components that I'm using:
- GNU Emacs 24.4.1 (i686-pc-mingw32)
- g++-4.9.2 (mingw-w64-x86_64)
- python-2.7 (Windows native version), also worked with python-3.4 (Windows native version)

@leodemoura and @htzh, could you let me know the results of `python --version` and `which python` inside of eshell?

**Comment by leodemoura** [comment] 2015-05-12 15:26
It is working for me now. It was a configuration problem. Everything works smoothly if I start emacs using `bin/leanemacs.bat`, and make sure my `.emacs` file does not mess the variables set in `bin/leanemacs.bat`.

I think a lot of the confusion is because `linja` does not terminate gracefully when it gets input that is not in the expected format.

Regarding this question

> @htzh, I think I got confused. So you don't have any problem in building/running Lean and the only problem is using it inside of emacs, right?

I believe his previous problem was fixed after he used the 64-bit MSYS2 to compile Lean.

**Comment by htzh** [comment] 2015-05-12 15:26
@soonhokong so there is a binary interface to Python? I see what is going on here, at least on my side: when I switched over to 64 bit built lean, I was still using 32 bit python in emacs. So I modded the the paths inside emacs now the 64 bit version no longer crashes. I will see if it is stable. This does not (yet) explain the 32 bit build instability.
My emacs is a standard windows native binary distro from GNU. mingw32 or 64  are not in my Windows PATH. They are set up automatically depending on which MSYS2 terminal I use. Emacs does not know about the existence of these and I have to put the correct path in site-start.el or init.el. So that is where the confusion comes from. @leodemoura  may have a similar problem.
Do you use system Python? Might be a good idea to pick the Python cmake found and used to build Lean and use that one inside Emacs as well. Could that configuration be built into cmake? You know people tend to have multiple versions of Python around. Some software even package their own Python.

**Comment by leodemoura** [comment] 2015-05-12 15:31
> This does not (yet) explain the 32 bit build instability.

BTW, it is not even clear to me whether 64-bit Windows + 32-bit MSYS2 is supposed to work.
This is not the standard way of building 32-bit binaries using MSYS2.
The MSYS2 website explicitly says one should use 64-bit MSYS2 with a 64-bit Windows.
Moreover, 64-bit MSYS2 can generate 32-bit binaries.

**Comment by leodemoura** [comment] 2015-05-12 15:32
Reference for previous claim:
http://sourceforge.net/p/msys2/wiki/MSYS2%20installation/

**Comment by leodemoura** [comment] 2015-05-12 15:43
@htzh In the Lean website, we provide a zip file with the pre-compiled binaries for Windows.
http://leanprover.github.io/download/wininst.html

**Comment by leodemoura** [comment] 2015-05-12 15:45
The zip file is updated everyday IF 
1- There are new commits 
2- The compilation succeeds, and the binary passes all tests

**Comment by htzh** [comment] 2015-05-12 15:45
@soonhokong @leodemoura just so we are on the same page, this is the sequence of event on my side:
1. There was a build problem #591 
2. There is also an emacs crashing lean server problem, which is reported in this thread, config mingw32 build and python
3. build problem in 1 was fixed by the patch in #591, both mingw32 and mingw64 build now.
4. mingw32 build is unstable; mingw64 build crashed on my machine due to a misconfiguration of Python
5. mingw64 build appears to work once the correct Python is picked inside emacs

> The MSYS2 website explicitly says one should use 64-bit MSYS2 with a 64-bit Windows.

I haven't had a problem with using the 32 bit msys2 and building apps using mingw32 before. Again there is a confusion of terminology: Msys2 comes in 32 bit and 64 bit flavors but that is just the shell. The toolchains and packages are separately installed as mingw32 or mingw64. So I don't think this is the cause of my problem. But I accept that my configuration is non-standard. I will happily use the mingw64 build of Lean if it is stable.

**Comment by htzh** [comment] 2015-05-12 15:55
Just to be clear: mingw32 refers to mingw-w64-i686 packages, mingw64 refers to mingw-w64-x86_64 packages. MSYS2 itself depends on cygwin dll so packages with msys prefix are not windows native. mingw32 and mingw64 packages are windows native and they are used to build native apps.

**Comment by soonhokong** [comment] 2015-05-12 15:59
@htzh,

> @soonhokong so there is a binary interface to Python?

No. Lean's emacs-mode calls `linja` which is written in Python.

> Do you use system Python?

I'm using the one that we can download from https://www.python.org/downloads/windows

**Comment by soonhokong** [comment] 2015-05-12 16:02
@leodemoura,

> I think a lot of the confusion is because linja does not terminate gracefully when it gets input that is not in the expected format.

I'll add code to handle corner cases in linja.

**Comment by htzh** [comment] 2015-05-12 16:06
> @htzh In the Lean website, we provide a zip file with the pre-compiled binaries for Windows.
> http://leanprover.github.io/download/wininst.html

That would still require the matching of the correct Python right? That is if your binary distro is built for 64 bit then the system Python picked in emacs must also be the 64 bit version. You might want to make that clear on the website.

> No. Lean's emacs-mode calls linja which is written in Python.

That is interesting! I am seeing dependence on which Python I use:
1. Python 3 does not build with mingw64 but Python 2 works.
2. mingw64 build crashes (in emacs) if using 32 bit Python but 64 bit Python works.

**Comment by leodemoura** [comment] 2015-05-12 16:09
@htzh I'm confused... the MSYS2 website (http://sourceforge.net/p/msys2/wiki/MSYS2%20installation/) provides two links 32-bit and 64-bit. It says one should use the 64-bit one for 64-bit Windows even if they want to build 32-bit binaries. Which one did you install?

> So I don't think this is the cause of my problem. But I accept that my configuration is non-standard.

For me, this is the most probable explanation.
I don't have a 32-bit Windows machine to test, but I believe the 32-bit tool chain will work on a 32-bit Windows. 
I have tested the 32-bit version on a Linux 32 bit VM, and did not find any problem. I tested 32-bit Lean using valgrind, and it did not report any problems in the Lean source code.

I see the following alternatives
1- use the pre-compiled Windows binaries from the Lean website
2- compile lean using the standard toolchain

I don't have the resources to support non standard configurations (e.g., 64-bit windows with 32-bit toolchain). If you want to do it, you will be very welcome, and I would be very grateful.

**Comment by soonhokong** [comment] 2015-05-12 16:12
@htzh,

> That would still require the matching of the correct Python right?

No. If there is any combination which does not work, it's a bug and I want to fix it. I just couldn't reproduce the previous one and it turned out that I was using the right combination.

> 1. Python 3 does not build with mingw64 but Python 2 works.
> 2. mingw64 build crashes (in emacs) if using 32 bit Python but 64 bit Python works.

I want to clarify the combinations which gave you problems. When we agree then I will reproduce them and fix them.
- Native 64-bit Python3 + Lean built by using mingw64
- Native 32-bit Python? + Lean built by using mingw64

Could you fill the '?' in the 2nd item above? Also, please feel free to add extra items to the list.

**Comment by htzh** [comment] 2015-05-12 16:57
@leodemoura I am fine with using the standard configuration. I am sorry to have caused what appears to be a wild goose chase. I will only report issues with the standard configuration from now on.

My problem appears to have been caused by using the mingw distributed Python (installed using pacman). I have switched to using Python distributed by python.org and the problem seems to have gone away with both mingw32 or mingw64 built Lean.

> @htzh I'm confused... the MSYS2 website (http://sourceforge.net/p/msys2/wiki/MSYS2%20installation/) provides two links 32-bit and 64-bit. It says one should use the 64-bit one for 64-bit Windows even if they want to build 32-bit binaries.

I have the 32 bit installer. The reason I don't believe it caused my problem is that the 32 bit here (if I remember correctly since I installed this long time ago and kept my system up-to-date using pacman) refers to the shell only, not the toolchain. There are 4 possible combinations: msys32/mingw32, msys32/mingw64, msys64/mingw32, msys64/mingw64. I have the first two combinations but toolchains are all native. I agree this is not the standard and from now on I will only report issues if it can be reproduced under msys64/mingw64 combination.

**Comment by soonhokong** [comment] 2015-05-12 17:04
> My problem appears to have been caused by using the mingw distributed Python (installed using pacman). 

I think this is problematic. I just changed the instructions in https://github.com/leanprover/lean/commit/651345a89bb7df252cc60362a3fdb165a92810f0.

**Comment by htzh** [comment] 2015-05-12 17:32
> I have the first two combinations but toolchains are all native.

By this I mean that it does not matter whether you have msys32 or msys64 you are running the same gcc/g++ packages. There is only one mingw64 g++ binary distribution and you are running the same one whether you have msys2 32 bit or 64 bit installed. The difference is that under msys32 bash is 32 bit while under msys64 bash is 64 bit. This was what the MSYS2 website warned about. This only affect programs in /usr/bin which are not native. The choice here does not affect native programs under /mingw32 or /mingw64. But just to be absolutely sure, I have downloaded the 64 bit msys2 installer and will install a fresh copy of msys64/mingw64.

**Comment by htzh** [comment] 2015-05-13 04:06
I have fresh started a new msys64/mingw64 to be on the safe side. It built Lean as expected. But lean.exe immediately crashed in Emacs. I also downloaded a binary distribution of lean from Lean website and it worked fine with Emacs. To find out why, I compared the DLL dependencies of the binary release and my own built lean:

```
# from Lean website
$ objdump.exe -x ~/w/proj/pkgs/lean-0.2.0-windows/bin/lean.exe |grep "DLL Name"
        DLL Name: libgmp-10.dll
        DLL Name: KERNEL32.dll
        DLL Name: msvcrt.dll
        DLL Name: libwinpthread-1.dll
        DLL Name: libgcc_s_seh-1.dll

$ objdump.exe -x /c/alt/msys64/usr/local/bin/lean.exe |grep "DLL Name"
        DLL Name: libgmp-10.dll
        DLL Name: lua53.dll
        DLL Name: KERNEL32.dll
        DLL Name: msvcrt.dll
        DLL Name: libwinpthread-1.dll
        DLL Name: libgcc_s_seh-1.dll
        DLL Name: libstdc++-6.dll
```

Note that the Lean built on my system has additional dependencies on lua53.dll and libstdc++-6.dll. It is surprising that the binary distribution of Lean also depends on many non-windows DLLs. In general there may be many versions of these DLLs lying around. For example on my system after I remove /mingw64/bin from PATH in a mingw64  shell I can still find the following:

```
$ which libgmp-10.dll
/c/alt/MinGHC-7.8.3/ghc-7.8.3/mingw/bin/libgmp-10.dll
$ which libwinpthread-1.dll
/c/alt/coq-bundle/bin/libwinpthread-1.dll
```

so the Lean binary distro was able to run without /mingw64/bin in the PATH, but my own binary crashes without it. I don't know why Windows does not show the traditional "DLL not found" message and instead just let Lean crash.

Anyway after I ensured in Emacs I have the right PATH setting:

```
       (setenv "PATH"
           (concat "c:/alt/Python34" ";"
               "c:/alt/msys64/mingw64/bin" ";"
               (getenv "PATH")
               ))
       (setq exec-path
         (append '("c:/alt/Python34"
               "c:/alt/msys64/mingw64/bin")
             exec-path))
```

now my own built binary also works with Emacs. This still does not explain everything but at least it seems reasonable enough so I won't pursue this matter further.

**Comment by htzh** [comment] 2015-05-13 05:45
As it turns out this saga continues. As I perform the test of merging two sections https://github.com/leanprover/lean/issues/593#issuecomment-100985467 my own built Lean binary crashed again, ~~but the binary from Lean site works. As I have made sure the environments are the same for the two, I am guessing the difference is due to DLLs bundled with the Lean binary distro: my own build depends on `lua53.dll libstdc++-6.dll` of my local mingw64 while Lean binary distro uses its own.~~ As I said my build was with all fresh msys2 (64) and mingw64.

**Comment by htzh** [comment] 2015-05-13 05:53
I can crash the binary distro from the website as well using the same cut test. It is not 100% reliable but it is fairly reliable. Okay so my own build and the binary distro behave about the same. The sad part is both crash.

**Comment by leodemoura** [comment] 2015-05-13 13:39
> I can crash the binary distro from the website as well using the same cut test. It is not 100% reliable but it is fairly reliable. Okay so my own build and the binary distro behave about the same. The sad part is both crash.

On my side, I downloaded the binary distro on a different machine, and edit your file for 30 min, I cut the block you pointed several times. I experienced no crash.
I started emacs using the `leanemacs` batch script in the binary distro.
Details:
- I put the binary distro at `C:\lean-0.2.0-windows`
- Python 2.7.8
- Emacs 24.4.50.1

Yesterday, you said the binary distro was working. What did it change? When did you start experiencing the crashes again?
Have you tried to compile Lean in debug mode?

Another experiment, in Emacs, go to the menu "Lean > Configuration". There are two check boxes: "Use flycheck (on-the-fly syntax check)" and "Show type at point". 
First, disable "Show type at point", and try to reproduce the crash. If you have time, it would be useful to try other configurations.

**Comment by htzh** [comment] 2015-05-13 16:28
> Yesterday, you said the binary distro was working. 

Sorry that was not clear. My build would not start at first but the binary distro would. That is when I thought it worked. Later on after more testing that turned out to be a premature judgement. There are so many possible combinations to check and it is triggered in the UI so I am sorry if some reports are not consistent.

I normally run emacs directly but I just tried leanemacs.bat from the binary distro as well. I tried starting it in a command prompt or from a mingw shell. I also removed my normal init.el. I tested Python 2.7.8 (32 bit) and Python 3.4.3 (64 bit). I tried turning off flycheck and type-at-point. I was still able to crash Lean.

If this is not reproducible by anyone else I can live with the current state since Emacs auto starts the Lean server after a crash. I am not equipped to debug UI issues. I will report again if I can find a non-UI based case or if the crashes happen so often as to be intolerable.

**Comment by leodemoura** [comment] 2015-05-13 16:36
> I tried turning off flycheck and type-at-point. I was still able to crash Lean.

@soonhokong I thought that Lean would not even be invoked when `flycheck` and `type-at-point` are disabled. Is that right?

@htzh When you say "crash Lean", I'm assuming you referring to `lean.exe`.

> If this is not reproducible by anyone else I can live with the current state since Emacs auto starts the Lean server after a crash.

It seems the `lean-sever` process is the one crashing. This is not the process created by `flycheck`.
@soonhokong Do you think it is possible the `lean-server` process is "silently" crashing on our machines and being restarted? Do you generate a message whenever the lean-mode restarts the lean-server?

**Comment by htzh** [comment] 2015-05-13 16:40
> When you say "crash Lean", I'm assuming you referring to lean.exe.

Yes. It has always been a Windows popup with the standard message "lean.exe has stopped working A problem caused ......"

**Comment by soonhokong** [comment] 2015-05-13 16:43
> @soonhokong I thought that Lean would not even be invoked when flycheck and type-at-point are disabled. Is that right?

No. When we edit a Lean buffer, it sends changes to lean-server to synchronize.

> @soonhokong Do you think it is possible the lean-server process is "silently" crashing on our machines and being restarted? 

I'm not sure. It is possible. But, I guess you do also have Visual Studio installed, right? I don't understand why you don't get the VS debug pop-up while @htzh gets one.

> Do you generate a message whenever the lean-mode restarts the lean-server?

Yes. See https://github.com/leanprover/lean/blob/master/src/emacs/lean-server.el#L241-L242 When we want to get a server process and failed to do so because a server process is not live. We force to restart it and log it to `_Messages_ buffer.

@htzh, when you visit `*Messages*` buffer, do you see a string starting with "lean-server-get-process"?

**Comment by leodemoura** [comment] 2015-05-13 16:45
> I'm not sure. It is possible. But, I guess you do also have Visual Studio installed, right? I don't understand why you don't get the VS debug pop-up while @htzh gets one.

I believe there is a configuration in the `registry` to disable/enable this behavior.
This is probably disabled on my machine. I will try to find out.

**Comment by htzh** [comment] 2015-05-13 16:48
> when you visit _Messages_ buffer, do you see a string starting with "lean-server-get-process"?

No I don't see the message but it seems to get restarted anyway since I can repeatedly trigger the same problem.

**Comment by htzh** [comment] 2015-05-13 16:55
I pushed the hom.lean I tested on to github. It has one line difference (a comment) from the previous HEAD.

**Comment by soonhokong** [comment] 2015-05-13 17:01
@htzh,

Could you provide an up-to-date list of combinations which you have problems? I wish to have the following information for each entry:
- Lean binary: Download from the webpage / Built by yourself using mingw (if so g++ version with 32/64-bit info)
- Python version : Native Windows / mingw ; 32-bit / 64 bit ; Python2 / Python3
- Problem: In the build process / In Emacs

Of course, you don't have to provide a complete list. Just let us know a couple of them. Some screenshot would be useful as well. Thank you.

**Comment by htzh** [comment] 2015-05-13 17:26
@soonhokong 
Problems are always in Emacs. No command line problems so far. Problems with both binary download and my own build (mingw 64, g++ 4.9.2) and Python 2.7.8 (32 bit) or 3.4.3 (64 bit) from python.org.

I tried an earlier version of my hom.lean 8c69a1caa34e6f3a70c6da8bb913ab1f610c66a5 I can reliably trigger the crash even easier by just pressing return after the "sorry" on line 31 (with the web download binary).

**Comment by soonhokong** [comment] 2015-05-13 18:05
@htzh, thanks for the info. I'll check them this evening.

**Comment by leodemoura** [comment] 2015-05-13 18:28
@htzh @soonhokong I managed to reproduce the crash. I believe it happens in all platforms, but we never noticed because lean-mode silently restarts the lean-server whenever it crashes. 
In @htzh system, the VS debugger is automatically invoked when an application crashes. This is why it experienced the bug. On his Linux machine, lean-server is also probably crashing, but he doesn't see it.
The bug is in the `lean-server`, this is the tool used to provide typing information and auto-completion to Emacs. This is why we never managed to reproduce the crash using the command line tools.

Here is the "recipe" to reproduce the crash using the command line:
1- Clone https://github.com/htzh/leanproved
2- `git checkout 8c69a1caa34e6f3a70c6da8bb913ab1f610c66a5`
3- Go to directory `leanproved/group_theory`, and compile the whole project using `linja`
4- Create the file `trace.input` with the following content

```
VISIT hom.lean
WAIT
INSERT 32

REPLACE 31
lemma ker.has_one (Hom : is_hom f) : 1 ∈ ker f := sorry
WAIT
```

5- Execute 

```
lean --server-trace trace.input
```

Then, we get the following output:

```
-- BEGINWAIT
-- ENDWAIT
-- BEGINWAIT
Segmentation fault (core dumped)
```

**Comment by htzh** [comment] 2015-05-13 18:59
@leodemoura Glad you are able to reproduce. Thanks.

**Comment by leodemoura** [comment] 2015-05-13 19:37
@htzh I found and fixed a problem in the lean-server background process. At least, the "recipe" in my previous message does not trigger the crash anymore.

**Comment by htzh** [comment] 2015-05-13 20:00
Yes I can confirm that it no longer crashes at either reported trigger points. The bug appears to be fixed. I will report if I see other incidences of crashing.

**Comment by soonhokong** [comment] 2015-05-13 20:01
@leodemoura, great! Thanks for solving the problem!!

**Comment by leodemoura** [comment] 2015-05-13 22:37
I'm closing this issue, we can reopen it if we find other problems.

**Closed as completed by leodemoura** 2015-05-13 22:37 UTC

**Comment by leodemoura** [comment] 2015-05-14 23:02
> Yes I can confirm that it no longer crashes at either reported trigger points. The bug appears to be fixed. I will report if I see other incidences of crashing.

@htzh Thank you for insisting this issue was a bug. At several points, I doubted you, and I apologize for that. Without your persistence, this bug would probably remain there for a very long time.

Thanks!

**Comment by htzh** [comment] 2015-05-14 23:50
@leodemoura Thanks for your gracious acknowledgement. At moments I doubted myself too. After getting bitten by some false starts I did spend a lot of time and effort trying out different combinations to double check what I reported. It is impressive how quickly you were able to fix it after you were able to reproduce the bug.
