### ISSUE TITLE
Parameters must be specified explicitly when definitions are used in tactics-mode proofs

### ISSUE THREAD

**Issue by cipher1024** [leanprover/lean3#1907] opened 2018-01-18 00:51 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

When, in a section inside a namespace, we use a parameter, in tactics proofs, definitions must be explicitly fed those parameters.

### Steps to Reproduce

Below, `test0` fails because we didn't give `hq` any parameter explicitly. `test1` and `test2` worked because `hq` is fully qualified.

```
namespace foo
section
parameters p q : Prop

parameters hp : p

include p q hp

lemma hq : q := sorry

lemma test0 : q :=
begin
  apply hq,
  -- p q : Prop,
  -- hp : p
  -- ⊢ ?m_1

  -- p q : Prop,
  -- hp : p
  -- ⊢ Prop
end

lemma test1 : q :=
begin
  apply foo.hq,
  -- no goals
end

end
end foo

section
parameters p q : Prop

parameters hp : p

include p q hp

lemma hq : q := sorry

lemma test2 : q :=
begin
  apply hq,
  -- no goals
end

end
```

**Expected behavior:** [What you expect to happen]

`apply hq` should finish the proof

**Actual behavior:** [What actually happens]

`apply hq` results in us having to provide a `p` and a proof for it.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

Lean (version 3.3.1, commit b3587e15a328, RELEASE)
and
in the online version

### OS

Mac OS X High Sierra, version 10.13.2

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Kha** [comment] 2018-01-18 10:17
Duplicate of #1773

**Closed as completed by Kha** 2018-01-18 10:17 UTC
