### ISSUE TITLE
Deep recursion in elaborator

### ISSUE THREAD

**Issue by gebner** [leanprover/lean3#1345] opened 2017-01-30 10:14 UTC
This happens with a long proof consisting of a few hundred apply tactics.  Lean runs for a minute and then fails with deep recursion detected.  However, we never even execute any tactic.  (I put `tactic.failed` as the first tactic to make sure of that.)

This is the file: https://gist.github.com/gebner/439273deee592603190d4f8b4447295b

**Comment by leodemoura** [comment] 2017-01-30 16:14
I can elaborate the term on my machine. It takes 25 secs.
Did you try to increase the amount of stack space? 
The `begin ... end` block is encoded using `pre_monad.and_then`. So, it is a deep term with depth > 1000.

**Comment by gebner** [comment] 2017-01-30 16:21
Ok, now I realized what went wrong.  I tried to set the stack size with `-j0`.  I was surprised to run into this limit so soon though.

**Comment by leodemoura** [comment] 2017-01-30 16:42
There are more than 1000 nested applications.
For each of them, we will execute `visit_app` >> `visit_app_core` >> `visit_base_app` >> `visit_base_app_core` >> `first_pass` and `second_pass`.
Just the `first_pass_info` (stack allocated structure) is 736 bytes. So, we have almost 1Mb of just `first_pass_info`. On my machine, it needs approx. 5Mb of stack space to process this file.

**Comment by leodemoura** [comment] 2017-01-30 16:49
We can optimize the code and save stack space if you think this is a relevant scenario.
That is, it reflects tactical proofs that will be written by users.

This one looks like an auto generated proof trace. If this is the case, another way to recover performance is to: create a data-structure for encoding these traces in a compact way, write a meta-program to execute the trace.

**Comment by gebner** [comment] 2017-01-30 16:53
> This one looks like an auto generated proof trace. If this is the case, another way to recover performance is to: create a data-structure for encoding these traces in a compact way, write a meta-program to execute the trace.

I think I'll do that.  Can we parse lists without using much stack space?  Then doing a `sequence' [apply ..., apply ..., apply ...]` should work and would be just as easy.

**Comment by leodemoura** [comment] 2017-01-30 16:58
> Can we parse lists without using much stack space?

I don't think the problem is the parser, but the elaborator.
A big list is also a deep term. If it has length `n`, then we have `n` nested `cons` cells.

**Comment by gebner** [comment] 2017-01-30 17:07
I think we should have an answer for long lists or vectors. Other people will try to use long literals as well.

I guess for now my best bet is to construct a binary `>>`-tree by hand.

**Comment by leodemoura** [comment] 2017-01-30 17:19
Binary tree is a good workaround.

To make it more convenient to use, we can add a builtin notation such as `#[a_1, ..., a_n]` that constructs the bintree for us. Then we can have a function that converts `bintree` into whatever we want `list`, `vector`, etc.

**Comment by leodemoura** [comment] 2017-01-30 17:22
BTW, did you investigate why it takes 25 secs to elaborate this example, or what the bottleneck is?
I'm trying to collect performance numbers.

**Comment by leodemoura** [comment] 2017-01-30 17:38
I got the performance numbers.
The first bottleneck is the bytecode compiler: 50% of the time is spent there, and most of the time is in the inliner. I think the problem is that `pre_monad.and_then` is marked as `[inline]`. So, the big`begin ... end` block becomes a term with hundreds of nested lambda applications. This should be easy to fix.

The second bottleneck is `is_def_eq` in the elaborator 42% of the runtime. We elaborate applications in two passes. In the first pass, we create a metavariable for each argument. We do it to be able to propagate information about the expected type to arguments. 
Example `add a b` becomes `@add ?A ?s ?arg_1 ?arg_2`, we infer the type (`?A` in this cases), unify it with the expected type (e.g., `nat`), and then execute the second pass, where elaborate the arguments using information propagated by the expected type. This is just overhead for a big `begin ... end` block. 

I think I can eliminate these two bottlenecks by changing how we encode the `begin ... end` blocks. I will try it later today.

**Comment by leodemoura** [comment] 2017-01-30 22:15
New numbers: 1.6 secs and less than 500Kb of stack space.

**Closed as completed by leodemoura** 2017-01-30 22:15 UTC
