### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by spl** [leanprover/lean3#1867] opened 2017-11-13 12:33 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

I'm not sure how to reduce the source to a minimal example. The problematic code depends on a lot of other code in my repository. If there are any suggestions, I'm happy to try. In the meantime, I'll give instructions on how to reproduce the problem using my repository.

### Description

The theorem [`acie.aeq.subst_comp.fresh_not_mem`](https://github.com/spl/alpha-conversion-is-easy/blob/0289f84656af61aea5ebb9c0f0f47749a102b35e/src/aeq/properties.lean#L49-L64) in [my repository](https://github.com/spl/alpha-conversion-is-easy/tree/0289f84656af61aea5ebb9c0f0f47749a102b35e) causes a segmentation fault. (In other words, you can comment out all of the other code in that file, and Lean will segfault.)

### Steps to Reproduce

1. `git clone https://github.com/spl/alpha-conversion-is-easy.git acie`
2. `cd acie`
3. `git checkout 0289f84656af61aea5ebb9c0f0f47749a102b35e`
4. `lean src/aeq/properties.lean`

**Expected behavior:**

Compile with errors.

**Actual behavior:**

`Segmentation fault: 11`

**Reproduces how often:**

Always

### Versions

```
$ uname -rs  # macOS Sierra 10.12.5
Darwin 16.6.0
$ lean --version
Lean (version 3.3.1, commit 426a9064bfbc, Release)
```

**Comment by spl** [comment] 2017-11-14 06:49
This issue is holding me back, so I thought I'd take a look at it. Any help would be appreciated.

I built `lean` with `-DCMAKE_BUILD_TYPE=DEBUG`. This is what I saw:

```
$ ./lean/bin/lean src/aeq/properties.lean
LEAN ASSERTION VIOLATION
File: /Users/leather/projects/alpha-easy/lean/src/library/type_context.cpp
Line: 1303
idx < m_tmp_data->m_eassignment.size()
(C)ontinue, (A)bort/exit, (S)top/trap, Invoke (G)DB
/Users/leather/projects/alpha-easy/src/aeq/properties.lean:67:0: error: type mismatch at application
  (λ {X : vs V} (e : exp X), Π {Y : vs V}, exp.subst X Y → exp Y) (exp.rec e_1 e_2 e_3)
term
  exp.rec e_1 e_2 e_3
has type
  Π (n : exp a), (λ {X : vs V} (e : exp X), Π {Y : vs V}, exp.subst X Y → exp Y) n
but is expected to have type
  exp a
C
LEAN ASSERTION VIOLATION
File: /Users/leather/projects/alpha-easy/lean/src/util/buffer.h
Line: 96
idx < size()
C
```

This repeats ad infinitum. I'm not yet sure what it means, but I'll study it more.

As an aside, on macOS when built with `clang`, should `lldb` be invoked instead of `gdb`?

```
G
INVOKING GDB...
sh: gdb: command not found
ERROR STARTING GDB...
```

**Comment by spl** [comment] 2017-11-14 08:04
I seem to be able to work around this issue by using `rw` instead of `simp`. See
https://github.com/spl/alpha-conversion-is-easy/commit/1e6ffc641c1223ff3286868ca2764ad36752a5c2:

```diff
-      simp [dif_neg (vname.ne_if_mem_and_not_mem (vname.map_of_subset _ x) (fresh X))]
+      rw [dif_neg (vname.ne_if_mem_and_not_mem (vname.map_of_subset _ x) (fresh X))],
```

**Comment by digama0** [comment] 2017-11-14 08:13
I haven't investigated this issue in detail, but it might be related to #1863. See if providing all implicits fixes the issue.

**Comment by digama0** [comment] 2017-11-14 08:24
Indeed, it looks like filling the underscore works:

    simp [vname.ne_if_mem_and_not_mem (vname.map_of_subset (vset.prop_subset_refl _) x) (fresh X)],

works for me. Closing as dupe of #1863

**Closed as completed by digama0** 2017-11-14 08:24 UTC

**Comment by spl** [comment] 2017-11-14 08:26
Thanks, @digama0.
