### ISSUE TITLE
cannot change buffer when Flycheck Error Messages is shown

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#617] opened 2015-05-21 06:09 UTC
Steps to reproduce:

0) Make sure the file `standard.lean` is _not_ opened in a buffer in Emacs
1) Create a file `test.lean` in the `library` folder, containing

``` lean
variable P : nat → Type

example : P (nat.of_num 1000) :=
begin
  esimp [nat.of_num]
end
```

2) In Emacs, move your point over `end` so that the `*Flycheck Error Messages*` buffer is shown.
3) Try to open `standard.lean` using `C-x C-f standard.lean`.
Result: The buffer `standard.lean` is opened, but the current buffer has not changed to `standard.lean` (it is still `test.lean`)
4) Executing `C-x C-f standard.lean` again works as expected, because `standard.lean` is now open.

(The fact that you open a `.lean`/`.hlean` file seems to matter, opening other files seems to work normally).

Jakob and I noticed this behavior already for a while, but we couldn't consistently reproduce it before.

**Comment by leodemoura** [comment] 2015-05-21 06:46
@soonhokong I managed to reproduce the problem. It is super weird. 
If we try multiple times, it eventually succeeds (at least for me). 
If we close `*Flycheck Error Messages*` buffer, it also succeeds.
Any ideas?

**Comment by soonhokong** [comment] 2015-05-21 13:03
@fpvandoorn and @leodemoura, I'll take a look at this one.

**Comment by soonhokong** [comment] 2015-05-21 15:31
I can reproduce the problem as well. I believe this is an upstream problem because the same problem happens when I try to open a C++ file. I will open an issue in flycheck repository.

**Comment by soonhokong** [comment] 2015-05-26 15:41
I opened an issue at https://github.com/flycheck/flycheck/issues/648.

**Comment by soonhokong** [comment] 2015-05-30 16:24
@fpvandoorn and @leodemoura, I have struggled with this issue. Today, I found a way to reproduce with a fresh emacs (`emacs -q`) and reported it to the flycheck author. I'll keep you posted the response.

He also suggested many points for improvements. I'll update `lean-flycheck.el` file by following them.

**Comment by leodemoura** [comment] 2015-12-14 00:14
@soonhokong Should we close this one?

**Comment by soonhokong** [comment] 2015-12-14 02:15
@leodemoura, I believe that this is an upstream issue. I just sent [this video](https://asciinema.org/a/dxfasmvyzn6omb6veic3cgfs6) to the author of flycheck-mode. I hope this help him fix the problem.

**Comment by leodemoura** [comment] 2015-12-14 02:31
Thanks!

**Comment by soonhokong** [comment] 2015-12-14 14:09
@leodemoura and @fpvandoorn, flycheck team confirmed that they can reproduce this problem without Lean-mode. See https://github.com/flycheck/flycheck/issues/648#issuecomment-164429830. However, it seems that it will take some time for them to fix it. 

@leodemoura, please feel free to close this issue here. I'll re-open it when I hear anything from the flycheck team

**Comment by leodemoura** [comment] 2015-12-14 15:36
@soonhokong Thanks for investigating this issue!

**Closed as completed by leodemoura** 2015-12-14 15:36 UTC

**Comment by soonhokong** [comment] 2015-12-15 00:00
The problem is fixed by the flycheck team. I'll write another comment when the patch is arrived at MELPA.

**Comment by fpvandoorn** [comment] 2015-12-15 01:25
Great! Thanks for your efforts to create an upstream example!

**Comment by soonhokong** [comment] 2015-12-17 15:52
@fpvandoorn, [the latest version of flycheck (20151216)](http://melpa.org/#/flycheck) is now available via MELPA. Please upgrade your flycheck and check you don't have this problem anymore.

**Comment by fpvandoorn** [comment] 2015-12-17 16:24
I updated flycheck and the problem is indeed solved. Thanks!
