### ISSUE TITLE
eq.subst produces a type mismatch when eta-expanded

### ISSUE THREAD

**Issue by mrhaandi** [leanprover/lean3#1827] opened 2017-09-20 08:46 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description
`eq.subst` produces a type mismatch when eta-expanded

### Steps to Reproduce
Consider the following lean code:

```lean
lemma example1 {a b : nat} : a = b → a < b → b < b := 
    eq.subst

lemma example2 {a b : nat} : a = b → a < b → b < b :=
    λ (h1 : a = b), eq.subst h1

lemma example3 {a b : nat} : a = b → a < b → b < b :=
    λ (h1 : a = b) (h2 : a < b), eq.subst h1 h2

lemma example3_explicit {a b : nat} : a = b → a < b → b < b :=
    λ (h1 : a = b) (h2 : a < b), @eq.subst _ _ _ _ h1 h2
```

**Expected behavior:**
All four examples should typecheck.

**Actual behavior:**
While `example1` and `example2` and `example3_explicit` typecheck, `example3` fails with the error message
```
"eliminator" elaborator type mismatch, term
  h2
has type
  a < b
but is expected to have type
  a < a
```
Note that `example3_explicit` does not provide more information than `example3`.

### Versions
Lean (version 3.3.1, commit d83b9ef3efbf, Release)
OS: Windows 10, 64bit

**Comment by Kha** [comment] 2017-09-20 09:04
Lean's surface syntax is not expected to allow eta expansion in every single context. Apart from elaborator hints, optional and auto parameters may break eta expansion as well.

**Comment by mrhaandi** [comment] 2017-09-20 10:47
> Lean's surface syntax is not expected to allow eta expansion in every single context.

I agree. However, I find it strange in this rather simplistic and fundamental (eq.subst/eq.rec) scenario.

Anyway, I added `example3_explicit`, which miraculously typechecks although it is supposed to be definitionally equal to `example3` which causes trouble.

**Comment by Kha** [comment] 2017-09-20 11:25
> However, I find it strange in this rather simplistic and fundamental (eq.subst/eq.rec) scenario.

While it should be possible to "fix" this behavior in the way you want, I believe it would be a very low-priority change. We expect users to basically always prefer using tactics for making substitutions.

> Anyway, I added example3_explicit, which miraculously typechecks although it is supposed to be definitionally equal to example3 which causes trouble.

`@` turns off elaboration strategy hints, see the end of https://leanprover.github.io/theorem_proving_in_lean/interacting_with_lean.html#elaboration-hints

**Comment by kbuzzard** [comment] 2017-09-21 09:44
Related: https://stackoverflow.com/questions/45385000/lean-eq-subst-chokes-on-hn-0

**Comment by spl** [comment] 2017-10-23 18:58
Related: https://groups.google.com/d/msg/lean-user/0uJcxklrU1w/YM7HX1gGAwAJ

**Comment by cipher1024** [comment] 2018-02-24 20:42
On the surface, it seems related to a problem I'm facing with the `subst` tactic.

In short, with `H : β = α`, `subst β` and `subst α` produce different results, i.e. one produces a type incorrect proof:

```
lemma subst_weirdness {α β : Type} {x : α} {P : Π t : Type, t → Prop}
  (H : β = α)
  (H' : P α x)
: P β (cast (by cc) x) :=
-- by { cases H, exact H' } -- works
by { subst β, exact H' } -- doesn't work
-- by { subst α, exact H' } -- works
```
Here is the error message I get on the second proof:

```
type mismatch at application
  eq.symm H
term
  H
has type
  β_1 = α
but is expected to have type
  β = α
types contain aliased name(s): β
remark: the tactic `dedup` can be used to rename aliases
```

**Comment by leodemoura** [comment] 2018-02-26 22:19
I'm closing this issue. This is not a bug. 
`eq.subst` uses the elaboration strategy: `[elab_as_eliminator]`. 
See: `#print eq.subst`
In this strategy, the motive is computed by abstracting all occurrences `b` in the expected type `b < b`.
Moreover, this strategy is only used if an `eq.subst` application is fully applied and `@` is not used.
Lean always use the default strategy when `@` is used.
To get the same behavior in all examples, we can use
```lean 
local attribute [elab_simple] eq.subst
```

**Closed as completed by leodemoura** 2018-02-26 22:19 UTC
