### ISSUE TITLE
-1 as integer through #eval may come out as 2147483647

### ISSUE THREAD

**Issue by kckennylau** [leanprover/lean3#1861] opened 2017-11-07 02:13 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

When passed through some functions, under `#eval`, negative integers may come out as the unsigned 32-bit version.

### Steps to Reproduce

```
def int' := int
#eval id_rhs int' (-1 : ℤ) -- 2147483647
```

### Versions

version 3.3.1, commit 1b4d2a850afd, Release

Windows 10

**Comment by digama0** [comment] 2017-11-07 02:18
The source of this bug is the default printing of VM exprs, which cannot differentiate between int and nat without typing information. Is this a won't fix? It's not obvious to me how to communicate the typing information in any reasonable way without changing the layout of VM objects.

**Comment by leodemoura** [comment] 2017-11-07 03:09
This is not a bug. The `#eval t` command tries to display the result using an instance of `has_repr T` where `t : T`. If the instance cannot be synthesized, it dumps the internal memory representation. 
If we declare an instance`has_repr int'`, we get the expected result. Example:
```lean
def int' := int

#eval id_rhs int' (-1 : ℤ)
-- #2147483647

instance : has_repr int' :=
by unfold int'; apply_instance

#eval id_rhs int' (-1 : ℤ)
-- -1
``` 
If `int'` is marked as `@[reducible]`, we don't need to add an instance.
```lean
@[reducible] def int'' := int

/- Don't need to define has_repr instance for int'' because it is reducible -/
#eval id_rhs int'' (-1 : ℤ)
-- -1
```
That being said, I will change the raw printer to produce `#2147483647` instead of `2147483647`. The idea is to make it clear that `#2147483647` is not the number `2147483647`, but its internal representation.
This is consistent with the current raw printer for constructor memory cells.

**Closed as completed by leodemoura** 2017-11-07 03:09 UTC

**Comment by leodemoura** [comment] 2017-11-07 03:25
I'm also adding a warning message when the `has_repr` instance cannot be synthesized.
