### ISSUE TITLE
Lean's convertibility is not transitive

### ISSUE THREAD

**Issue by maximedenes** [leanprover/lean3#722] opened 2015-07-05 16:03 UTC
This is probably known since it is very related to issue #654. Following a remark by Matthieu Sozeau, I was investigating how Lean could deal with singleton elimination and proof irrelevance and noticed that convertibility is not transitive at the moment.

Of course, feel free to close the issue if it is considered as a feature of the formalism.

Here is a concrete example, using acc:

open nat

definition wf_nat (n : nat) : acc lt n :=
match lt.wf with
| well_founded.intro p := p n
end

/- f always returns 0 -/
definition f : ∀n : nat, acc lt n -> nat
| f 0 p := 0
| f (succ m) (acc.intro _ p) :=
    f m (p _ (le.refl (succ m)))

/- a is convertible to b -/
check (eq.refl _ : (λp, f 1 p) = (λp, f 1 (wf_nat 1)))

/- b is convertible to c -/
check (eq.refl _ : (λp, f 1 (wf_nat 1)) = (λp, 0))

/- but a is not convertible to c -/
check (eq.refl _ : (λp, f 1 p) = (λp, 0))

**Comment by leodemoura** [comment] 2015-07-05 17:38
Dear Maxime,

Thanks for posting the issue. Yes, this issue is very related to #654. 
The trick discussed at #654 could be used to address this issue. In the third `check`, it would replace `p` with `acc.intro 1 (fun y h, acc.inv p h)` and "unblock" the computation, and both sides would reduce to `λp, 0`. Unfortunately, this trick makes the convertibility checker non-terminating. We thought about limiting the number of times it can be applied, but we would be "sacrificing" transitivity again.

We also considered defining `acc` in `Type`, and removing singleton elimination from the kernel.
This is also not nice, if we do that, I don't see how to define 

``` lean
find_x : (∃ a : nat, p a) → {a : nat | p a}
```

https://github.com/leanprover/lean/blob/master/library/data/nat/choose.lean#L96

Comments about this issue and #654 would be very welcome. This is one of the things that keep me awake at night :-)
Are you considering supporting OTT in Coq?

Best wishes,
Leo

**Comment by leodemoura** [comment] 2015-07-09 11:38
@avigad @fpvandoorn any thoughts?
I'm planning to add a link from #654 and close it.

**Comment by avigad** [comment] 2015-07-09 12:06
Maxime's example is nice. I think it is a good idea to link from #654 and close this issue. So far, singleton elimination and proof irrelevance have been quite useful, and I don't think we have noticed any bad effects of the failure of transitivity. So I can't think of any immediate action that would be appropriate. But we should definitely keep this in mind as we figure out how to use computation in Lean.

**Comment by fpvandoorn** [comment] 2015-07-10 11:00
I agree that we can link from #654 and close this. This behavior is worrisome but it's hard to find a good solution. The trick described in #654, but restricted to closed terms won't solve this issue, right?

**Comment by leodemoura** [comment] 2015-07-10 11:23
> The trick described in #654, but restricted to closed terms won't solve this issue, right?

We can use it for any kind of term. The problem is that the convertibility checker may loop.

**Comment by leodemoura** [comment] 2015-07-11 23:40
Added link from #654 to this one, and closed.

**Closed as completed by leodemoura** 2015-07-11 23:40 UTC
