### ISSUE TITLE
`0 + 1 =?= 1` fails for nats with reducible setting 

### ISSUE THREAD

**Issue by dselsam** [leanprover/lean3#1226] opened 2016-12-06 03:25 UTC
The following rewrite fails (using `reducible`):
```Lean
inductive vec (α : Type*) : ℕ → Type*
| nil {} : vec 0
| cons   : α → Π {n : nat}, vec n → vec (n+1)

namespace vec
def head {α : Type} : Π {n : ℕ}, vec α (n+1) → α
| n (cons x xs) := x
end vec

constants (dret : Π {n : ℕ}, vec nat n → (vec nat n → nat) → nat)
axiom dret_spec : Π {n : ℕ} (xs : vec nat n) (f : vec nat n → nat), dret xs f = f xs

set_option trace.type_context.is_def_eq true
set_option trace.type_context.is_def_eq_detail true

example (v : vec nat 1) : dret v vec.head = vec.head v := by rw dret_spec
```
The trace shows why:
```
[type_context.is_def_eq_detail] [3]: 0 + 1 =?= 1
[type_context.is_def_eq_detail] [4]: add =?= one
[type_context.is_def_eq_detail] on failure: add =?= one
[type_context.is_def_eq_detail] on failure: 0 + 1 =?= 1
```

We have been discussing different delta-annotation/reduction strategies for a long time now, and this example is just one of many edge cases we have hit at various times. I think the key idea that we discussed over the summer that may enable a cleaner design is to use `refl` lemmas in `is_def_eq` (and perhaps elsewhere in the type-context). Although we almost never want `+` to be _unfolded_, we almost always want `0 + 1 ==> 1` to be _(d)simplified_. 

Note: there will be many details and complications in implementing such an approach. I am not, as part of this Github issue, proposing a complete solution, but rather am noting it as an outstanding issue along with a potential approach to addressing it. We can discuss details over a different medium.

**Comment by leodemoura** [comment] 2016-12-06 04:48
I had many problems when I tried `refl` lemmas in `is_def_eq`. I solved some of them, but I gave up. It is a mess. Here are the notes I wrote after I tried:

See branch: https://github.com/leodemoura/lean/tree/type_context_with_refl_lemmas
Problems: 
1) We have to be able to rewrite even when the type context is already in tmp mode.This is an issue because the tmp metavariables in the `refl` lemma clash with the ones created in the type context. Solution: implemented lift operation for idx metavariables, and custom match 

2) The term being "unfolded" may be stuck. Example:
```
          nat.add n (@one nat ?m)  
```
       will not match the pattern
```
          nat.add ?x_0 (nat.succ ?x_1)
```
because `?m` is not assigned yet. We can assign it during the matching process because it is a regular metavariable and the matching is performed in tmp mode. 

Possible workaround a) try to instanciate type class instances before we try the `refl` lemmas. This is a potential performance problem because the term can be arbitrarily big. The current heuristics we use to speed up the process do not work for the example above.
       
Possible workaround b) allow regular metavariables be assigned by type class resolution even when we are in tmp mode.
       
3) There are many more lazy-delta steps. Before this feature, when we unfold `nat.add a (succ ... (succ b) ...)`, we are done with delta-reduction. It is just iota and beta after that. However, with `refl` lemmas, the term `nat.add a (succ ... (succ b) ...)` produces one lazy-delta step per `succ`.This produces nasty side-effects because of the The heuristic `(f t =?= f s) ==> (t =?= s)`. Examples such as
```
          (fib 8) =?= 34
```
will take a very long time because of this heuristic. Possible workaround: cache failures like we did in Lean2. However, failure are only easy to cache if there are no meta-variables.
  
4) The type context trace gets very confusing since we use `is_def_eq` for matching `lhs` while we are computing `is_def_eq`. Possible workaround: disable trace when trying `refl` lemmas.

5) We must be able to temporarily disable the feature. Example: when proving a `refl` lemma for a definition `f`, we may have to expand the nested definitions (e.g., for match-end blocks)

6) refl/simp lemmas were designed to rewrite elaborated terms. Using them during unification may produce a series of unexpected behaviors since terms contain regular and universe meta-variables. 

7) We need to define a notion of "refl stuck application". Right now, a metavar is stuck, a projection is stuck if the structure is stuck, a recursor is stuck is the major premise is stuck. An application `f ...` is `refl` lemma stuck if `f` has `refl` lemmas associated with it, AND metavariables occurring in arguments are preventing a `refl` lemma from being applied.

**Comment by dselsam** [comment] 2016-12-06 05:03
Thank you for the thorough report. I will think about these issues. My immediate gut reaction is that we may get >80% of the benefit with <20% of the pain if we only try the `refl` lemmas on terms without meta-variables. Since most of elaboration is done at `semireducible`, the issue I mentioned above doesn't manifest there (although unfolding does expose a lot of complexity when solving `0 + 1 =?= 1` at `semireducible`). The main pain-point is tactics that need or ought to be at `reducible`, and these tactics will mostly operate on fully elaborated terms.

**Comment by leodemoura** [comment] 2016-12-06 05:46
> My immediate gut reaction is that we may get >80% of the benefit with <20% of the pain if we only try the refl lemmas on terms without meta-variables.

This will not solve issues 1, 3, 4. 

If the goal is to handle only terms without meta-variables, then there is a much simpler solution:
we temporarily switch to semi-reducible. 
If this is too expensive, we can switch only when the heads are marked with a new attribute.

Recall that we wanted to use `refl` lemmas to make sure meta-variables get nice solutions.
Example: `?m + 1 =?= succ n`,

**Comment by leodemoura** [comment] 2016-12-06 08:13
Update: using `refl` lemmas nor switching to semi-reducible (for constraints `t =?= s` that do not contain meta-variables) are not satisfactory solutions. Lean cannot even compile the standard library using this approach.

I added a new attribute to control the heuristic, and marked only `add`, `nat.add`, `bit0`, `bit1`, `one` and `zero` with it. Then, I managed to compile the standard library with no overhead. However, two regression tests failed. The main issue is that we don't want to use this heuristic for a unification constraint such as `10000 + 10000 =?= 20000` (it will take a long time to solve it), nor a constraint such as `10000 =?= 10001` (it will take a long time to fail).

Alternative solutions considered so far:

1- Allow user to provide their own callback (written in Lean) for deciding whether the constants in a unification constraint should be unfolded or not. Cons: this will slow down the whole system. 
The method `on_is_def_eq_failure` is called millions of times.

2- Hard code a solution for handling unification constraints built using only `+`, `succ`, locals, and numerals, and use it at `on_is_def_eq_failure`. It would only consider small constants.
This will probably solve the problem, but is too hackish.

3- Add notation `#n` for `nat.succ (nat.succ (... nat.zero))`. We would encode vector indices using `succ` and `#n` numerals. So, there is no unfolding going on. This is super ugly and will generate confusion.

4- Encode natural numbers less than some small `n` using `nat.succ` and `nat.zero` instead of `bit0`, `bit1`, `zero` and `one`. The value `n` is a configuration option. Of course, this would create a different class of problems. For example: `rw zero_add` would fail at `a : nat |- p (0 + a)`. Reason: `@zero nat nat.has_zero =?= nat.zero`. We can try to address this issue using unification hints.

5- Use unification hints. We would also have problems with timeouts. For example, we would thousands of unification hint applications to be able to solve `10000 + 10000 =?= 20000`.

6- Temporarily mark `add`, `bit0`, `bit1`, `one` and `zero` as reducible at `rw` and `simp` variants. 
Cons: It would be super annoying to use these variants, and they would probably fail on examples that produce constraints such as `10000 =?= 100001`.

I think I will use approach 2), it is hackish, but I hope we will not find similar instances of this problem very often. Note that, the problem only happens because of the generic encoding we use for numerals, and the encoding is implemented in C++.

**Comment by dselsam** [comment] 2016-12-06 15:40
> 2- Hard code a solution for handling unification constraints built using only +, succ, locals, and numerals, and use it at on_is_def_eq_failure. It would only consider small constants.
This will probably solve the problem, but is too hackish.

> I think I will use approach 2), it is hackish, but I hope we will not find similar instances of this problem very often. Note that, the problem only happens because of the generic encoding we use for numerals, and the encoding is implemented in C++.

This seems like an adequate solution.

**Comment by leodemoura** [comment] 2016-12-06 16:27
BTW, we can also avoid the problem by using the `erw` tactic (aka `erewrite`). 
It is more expensive since it also unfolds semireducible constants during unification. 
```
meta def erewrite : qexpr_list_or_qexpr0 → location → tactic unit :=
rw_core semireducible
```
A similar tactic for `simp` can also be built, but it will probably be too expensive.

@kha I believe you had similar problems in your project. Any suggestions?

**Comment by dselsam** [comment] 2016-12-06 16:48
FYI yesterday I tried running the simplifier at `semireducible` and it was orders of magnitude slower.

Note: I did not isolate the reasons, and it may have been severely exacerbated by the presence of string literals in the goal (see #1218)

**Comment by leodemoura** [comment] 2016-12-06 22:26
Update: approach 2) doesn't work. Well, it works for the example used in this issue, but it fails at:
```
example (v : vec nat 6) : dret v vec.head = vec.head v := by rw dret_spec
```
The main problem is how to efficiently recognize when the heuristic is applicable.
In my implementation, I was checking for subterms constructed using `bit0`, `bit1`, `one`, `zero`, `nat.succ`, `add`, `nat.zero` and locals. In the example above, it fails on the following unification constraints.
```
succ
  (prod.fst
     (prod.fst
        (nat.rec
          (λ (a : ℕ),
            nat.cases_on 0 (λ (_F : nat.below 0), a)
              (λ (a_1 : ℕ) (_F : nat.below (succ a_1)), succ (prod.fst (prod.fst _F) a))
              poly_unit.star, poly_unit.star)
          (λ (a : ℕ) (ih_1 : (ℕ → ℕ) × nat.below a),
             (λ (a_1 : ℕ),
               nat.cases_on (succ a) (λ (_F : nat.below 0), a_1)
                 (λ (a : ℕ) (_F : nat.below (succ a)), succ (prod.fst (prod.fst _F) a_1))
                 (ih_1, poly_unit.star), ih_1, poly_unit.star))
          (prod.fst
             (prod.fst
                (nat.rec
                  (λ (a : ℕ),
                    nat.cases_on 0 (λ (_F : nat.below 0), a)
                      (λ (a_1 : ℕ) (_F : nat.below (succ a_1)), succ (prod.fst (prod.fst _F) a))
                      poly_unit.star, poly_unit.star)
                  (λ (a : ℕ) (ih_1 : (ℕ → ℕ) × nat.below a),
                     (λ (a_1 : ℕ),
                       nat.cases_on (succ a) (λ (_F : nat.below 0), a_1)
                         (λ (a : ℕ) (_F : nat.below (succ a)), succ (prod.fst (prod.fst _F) a_1))
                         (ih_1, poly_unit.star), ih_1, poly_unit.star))
                  0, poly_unit.star))
             1), poly_unit.star))
     3) + 1 
=?= 
6
```
Both sides are definitionally equal, but we need a lot of normalization to detect it.

Now, I'm wondering whether we should add this kind of heuristic to the unifier (`is_def_eq` procedure).  It seems every new feature we try to add produces a lot of unexpected behavior and performance problems.

By looking at the traces of the these examples, I observed that the system is already solving messy unification problems. Example `?m + 1 =?= 3 + 3` in the example above during elaboration.
The solution for `?m` is the mess above.

Here are some lessons.
- If we want to use automation (e.g., simplifier, SMT-like techniques, E-matching, etc), then unification should be cheap. 
- Definitions such `head` create messy unification problems. The problem is aggravated by the way we encode natural numbers in Lean.  Here are some alternative signatures for `head`
a) `def head {α : Type} : Π {n : ℕ}, vec α n → n > 0 → α`, unification is simpler, but we need to discharge side conditions.
b) `def head {α : Type} [inhabited α]: Π {n : ℕ}, vec α n → α`, see the following comment https://github.com/leanprover/lean/commit/1ebe2b590de77751bcd3aae816fa2baf5b371f7d#commitcomment-19938972

- If we want to define `head` as `def head {α : Type} : Π {n : ℕ}, vec α (n+1) → α`, and use automation, then we must make sure the unification problems are simple. We can accomplish that by using `succ n` instead of `n+1`, and using an unary encoding for small nat numerals. 

- To make approach 2) work, we would need to add support for producing nice solutions for constraints such as `?m + 1 =?= 3 + 3`. That is, `?m := 5` instead of the messy `?m := succ (prod.fst ...)`

**Comment by Kha** [comment] 2016-12-07 00:15
> @kha I believe you had similar problems in your project. Any suggestions?

I think I once posted a goal like
```
le_max_cost : k ≤ cmp_max_cost
⊢ 0 + (0 + 0 + (1 + 0)) + 0 + (0 + k + 1) + (0 + 0 + 0 + 1) + (1 + 0 + 0 + 1 + 5 + 1 + 1) ≤ cmp_max_cost needle self + 15
```
which I eventually solved by first doing a manual normalization, then applying `dec_trivial`.
```
repeat (rewrite [{k + _ + _}add.assoc] | rewrite [-{_ + (k + _)}add.assoc] |
        rewrite [{_ + k}add.comm]),
apply add_le_add hle_max_cost dec_trivial
```

I'm afraid I'm not familiar enough with the implementation-level problems to make any suggestions.

**Comment by leodemoura** [comment] 2016-12-07 01:11
Update: The commit above adds support for "offset constraints". That is, unification constraints of the form
```
t_1 + k_1 =?= t_2 + k_2
t_1 + k_1 =?= k_2
k_1 =?= t_2 + k_2
k_1 =?= k_2
```
where `k_1` and `k_2` are (small) numerals, `t_1` and `t_2` are arbitrary terms, and the type is `nat`.
Right now, the threshold for "small numerals" is hard coded (256). The threshold is used to make sure it doesn't succeed on constraints such as `200000 + 200000 =?= 400000` that would take an extremely long time to check in the kernel using normalization.
If we decide to keep this feature, I will add a new configuration option. The performance impact seems to be very small, and all regression tests passed. This is a hackish solution, but is the only one that worked, and doesn't require us to change how we encode numerals or vector/bitvector operations such as `head`.

**Comment by leodemoura** [comment] 2016-12-07 01:11
I will keep this issue open until we decide whether the solution above is satisfactory or not.

**Comment by dselsam** [comment] 2016-12-07 02:04
I like the solution you implemented. Even if we universally adopt the style @Kha advocates in the comment you linked to, I would be surprised if `0 + 1 =?= 1` failing at `reducible` never shows up again. It is a nice bonus that these problems are now solved quickly at `semireducible` without unfolding. I am ready to close this issue if others agree.

Aside: I know you are already aware of this, and it is not a problem and not worth addressing, but just for the record I'll flag something that might confuse somebody at some point:
```Lean
example (v : vec nat (id 1)) : dret v vec.head = vec.head v :=
by rw dret_spec -- fails, even when id is reducible
```
`try_nat_offset_cnstrs` is only tried once at the beginning of `is_def_eq`, so if the constraint is only exposed after a delta step the heuristic will not trigger.

**Comment by leodemoura** [comment] 2016-12-07 02:09
> try_nat_offset_cnstrs is only tried once at the beginning of is_def_eq, so if the constraint is only exposed after a delta step the heuristic will not trigger.

I will move into to the `lazy_delta` loop.

**Comment by leodemoura** [comment] 2016-12-07 02:09
> Right now, the threshold for "small numerals" is hard coded (256)

Any suggestions for the option name? :)

**Comment by leodemoura** [comment] 2016-12-07 02:11
> I am ready to close this issue if others agree.

Good. Could you please experiment more with it before we close it?

I will add the configuration option for setting the threshold, and move the heuristic to the `lazy_delta` loop.

**Comment by dselsam** [comment] 2016-12-07 02:17
> Any suggestions for the option name? :)
Do you expect the performance overhead to be so noticeable that we really need an option to turn it off? It is conceivable that it actually speeds most developments up, depending on how many such constraints were previously being solved at `semireducible` by unfolding.

**Comment by dselsam** [comment] 2016-12-07 02:19
`set_option unifier.nat_offset_cnstr_threshold 256`?

**Comment by dselsam** [comment] 2016-12-07 02:20
> Could you please experiment more with it before we close it?

Yes, tomorrow morning.

**Comment by dselsam** [comment] 2016-12-07 17:07
I'll point out two very minor issues. I am still happy with the solution.

1. Different instances in `bit0` and `bit1` are only caught in the kernel
```Lean
constants (nat_has_add₂ : has_add ℕ)
          (α : ℕ → Type)
          (f : Π {n : ℕ}, α n → α n)
          (foo : ∀ {n : ℕ} (x : α (n + @bit0 ℕ nat_has_add₂ 1)), f x = x)

example (x : α 2) : f x = x := by rw foo -- fails
/-
error: type mismatch at application
  @eq.rec (α (0 + 2)) x
term
  x
has type
  α 2
but is expected to have type
  α (0 + 2)
-/
```
We could address this by checking the instances at 
https://github.com/leanprover/lean/blob/master/src/library/type_context.cpp#L2473
https://github.com/leanprover/lean/blob/master/src/library/type_context.cpp#L2478

2. Right now we check instances based on constant names as opposed to definitional equality. I think this is appropriate for performance reasons, but I'll flag a potentially confusing consequence for the record. 
```Lean
constants (α : ∀ {X : Type}, X → Type)
          (f : Π {X : Type} {n : X}, α n → α n)
          (foo : ∀ {X : Type} [comm_semiring X] (n : X) (x : α (n+1)), f x = x)

example (x : α (1:ℕ)) : f x = x := by rw (@foo ℕ _) -- fails
/-
[type_context.is_def_eq_detail] [2]: @add nat (@distrib.to_has_add nat (@distrib_of_semiring nat (@comm_semiring.to_semiring nat nat.comm_semiring))) ?m_132
  1 =?= 1
[type_context.is_def_eq_detail] [3]: add =?= one
[type_context.is_def_eq_detail] on failure: add =?= one
[type_context.is_def_eq_detail] on failure: @add nat (@distrib.to_has_add nat (@distrib_of_semiring nat (@comm_semiring.to_semiring nat nat.comm_semiring))) ?m_132
  1 =?= 1
-/
```

**Comment by leodemoura** [comment] 2016-12-08 00:27
> 1. Different instances in bit0 and bit1 are only caught in the kernel

I'm checking only the the instances of `+`, `0` and `1`. 
These checks are actually needed. Otherwise, lean fails to compile the standard library because of the why we encode `semiring` using renaming.

The constants bit0` and `bit1` are "internal" constants used to encode numerals.
I'm not expecting anybody to use them directly, let alone redefine the instances for `nat`.

> 2. Right now we check instances based on constant names as opposed to definitional equality. I think this is appropriate for performance reasons, but I'll flag a potentially confusing consequence for the record.

I think the example you used is very unrealistic. I doubt this kind of example will happen in practice.
If it does, we can use `is_def_eq` and reorganize the code to minimize the performance impact.

**Closed as completed** 2016-12-08 19:40 UTC
