### ISSUE TITLE
Trouble with subtype inference of decidable

### ISSUE THREAD

**Issue by htzh** [leanprover/lean3#713] opened 2015-06-27 05:20 UTC
I am having trouble with the inference of the decidable instance for a subtype. So I am manually supplying a variable for now:

https://github.com/htzh/leanproved/blob/ccde97cd45bef4a1cc465fbf34b120b1bdce2856/group_theory/pgroup.lean#L226

```
lemma rotl_perm_ps_pow_eq {n i : nat} [d : decidable_eq (peo_seq A n)] : (rotl_perm_ps A n 1)^i = (rotl_perm_ps A n i) := sorry
```

`print instances decidable` shows that I have the required parent instance:

```
subtype.has_decidable_eq : Π {A : Type} {P : A → Prop} [H : decidable_eq A] (s₁ s₂ : subtype P),
  decidable (s₁ = s₂)
```

Note I must supply the exact `decidable_eq (peo_seq A n)`. If I supply the parent type `decidable_eq (seq A n)` it does not type check.
I don't have any problem with inferring the decidability for the parent type as demonstrated here:
https://github.com/htzh/leanproved/blob/ccde97cd45bef4a1cc465fbf34b120b1bdce2856/group_theory/cyclic.lean#L455

**Comment by leodemoura** [comment] 2015-06-29 16:48
`peo_seq` is not reducible. The type class resolution engine only unfolds `[reducible]` definitions.
You can avoid `[d : decidable_eq (peo_seq A n)]` by marking `peo_seq` reducible.
If you don't want it to be `[reducible]` everywhere, then you can use

``` lean
local attribute peo_seq [reducible]
```

This restriction on type class resolution was added for performance reasons and for preventing non-termination. Note that, type class resolution creates many unification problems that do not have solution. We want them to fail quickly. So, a trick is to minimize the number of definitions that will be unfolded by this procedure.

**Comment by leodemoura** [comment] 2015-06-29 16:49
I'm closing this issue since it is not a bug.

**Closed as completed by leodemoura** 2015-06-29 16:49 UTC

**Comment by htzh** [comment] 2015-06-29 23:59
Thanks! I forgot the [reducible] requirement (again :-().
