### ISSUE TITLE
Installing Lean on Windows 10

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#835] opened 2015-09-26 18:59 UTC
I installed Windows 10 on my laptop, and I tried if the installation instructions for Windows 8 worked for me.

However, when I open a Lean file, Emacs freezes after ~10 seconds (even when doing nothing), and Flycheck displays "FlyC*". 

Emacs and Python are in my path.

Can I send more information which could be helpful? The only thing which looked strange is that the `cmd` screen opened when running `leanemacs.bat` displays paths which have `\/` in them:

```
D:\Programs\Lean\lean-0.2.0-windows\bin>SET MY_PATH=D:\Programs\Lean\lean-0.2.0-windows\bin\

D:\Programs\Lean\lean-0.2.0-windows\bin>SET LEAN_ROOTDIR=D:\Programs\Lean\lean-0.2.0-windows\bin\/..

D:\Programs\Lean\lean-0.2.0-windows\bin>SET LEAN_EMACS_PATH=D:\Programs\Lean\lean-0.2.0-windows\bin\/../share/emacs/site-lisp/lean

D:\Programs\Lean\lean-0.2.0-windows\bin>emacs -load D:\Programs\Lean\lean-0.2.0-windows\bin\/../share/emacs/site-lisp/lean/load-lean.el
```

**Comment by soonhokong** [comment] 2015-09-27 16:38
@fpvandoorn, can I visit your office and check somethings, let's say..., sometime tomorrow afternoon?

**Comment by fpvandoorn** [comment] 2015-09-27 17:18
Ok, then I'll bring my laptop tomorrow. My office is Doherty Hall 4301B.

**Comment by leodemoura** [comment] 2015-09-27 17:26
@soonhokong Thanks a lot for taking care of this issue.

**Comment by soonhokong** [comment] 2015-09-28 16:25
@fpvandoorn, please send me an email when you have some time this afternoon, I'll visit your office then.

**Comment by soonhokong** [comment] 2015-09-29 21:55
For the record, it was because `lean.exe` was not in the `PATH` environment variable. After adding `lean/bin` directory into `PATH`, the problem goes away.

I'll update the documentation and close this issue tonight. @fpvandoorn, I will also try to add `unicode-fonts` emacs package into lean-emacs.

**Comment by fpvandoorn** [comment] 2015-09-30 03:14
Great!

**Comment by soonhokong** [comment] 2015-09-30 07:35
@fpvandoorn, I'm testing it on a Windows7 machine and it works without adding `lean/bin` to `PATH` env variable.

Could you test the following things on your Windows 10 machine?
- remove `.../lean/bin` from your `PATH` env variable (to reproduce the problem)
- launch `leanemacs`, open a `.lean` file, make sure that you have the problem.
- press <kbd>C-h v</kbd>`lean-rootdir`. It will show the current value of `lean-rootdir` variable. Please copy/paste it here.

FYI, it works in the following ways (at least in Windows7):
- `LEAN_ROOTDIR` is set up in https://github.com/leanprover/lean/blob/master/bin/leanemacs.in#L5
- and it's loaded into emacs at https://github.com/leanprover/lean/blob/master/src/emacs/load-lean.el#L3-L5

It's possible that the above is not working in Windows 10 anymore (because of some reasons).

You also told me that the effect of `setx` seemed to be temporary (not permanent). I looked up some references but [a link](https://technet.microsoft.com/en-us/library/cc755104.aspx) says that it's effect is permanent. Could you double-check it (it might be difficult)? Note that it seems the effect of `set` is limited to the current session.

**Comment by soonhokong** [comment] 2015-09-30 07:37
@fpvandoorn, another useful information is the result of <kbd>M-x</kbd>`version`.

**Comment by fpvandoorn** [comment] 2015-10-01 01:59
I cannot reproduce the original problem anymore. I removed `Lean` from my path and now Flycheck works as normally. I don't know what changed since then.

However, there is a problem with the installation instructions

```
> setx PATH "%PATH%;c:\Python27\"
> setx PATH "%PATH%;c:\emacs\bin"
```

[This](http://stackoverflow.com/a/26947177) answer on stackoverflow explains it well. In short: there is a SYSTEM path and a USER path in Windows. `%PATH%` is the concatenation of both, so the commands above concatenate the system and the user paths, and store that value in the user path. There is another problem that for some reason `setx` truncates the path to 1024 characters for some unknown reason. 

The comment below the answer advises against using `setx` to change the PATH at all, so maybe it's best to completely remove the option to change the path using `cmd`, and only offer the instructions by GUI.

I think my original problem was somehow caused by messing up my path variable in this way... But I cannot reproduce it even if I try it again (I don't know the exact actions I took last time).

Also, I'm quite sure that I thought that `setx` was temporary because of the truncation to 1024 characters: I added a directory to the PATH via GUI after the 1024 "allowed" characters, and then ran `setx` again later, which effectively removed the added directory.

Lastly, Python (at least Python 3.5) offers a checkbox "add Python to PATH". If you check that you don't have to do it manually. Maybe we should mention that in the installation instructions.

**Comment by fpvandoorn** [comment] 2015-10-01 02:48
Another problem. I added the Emacs mode for Lean to my `.emacs` file, as descibed here, under case 4: https://github.com/leanprover/lean/blob/master/src/emacs/README.md
After this, when Emacs loads up it complains that it cannot find `lean-mode`.

`C-h v load-path` gives

```
load-path is a variable defined in `C source code'.
Its value is
("D:\\Programs\\Lean\\lean-0.2.0-windows\\bin\\/../share/emacs/site-lisp/lean"
[bunch of other stuff (including some subfolders of the previous path)])
```

So I'm not sure why it cannot find `lean-mode`.

When I add

```
(add-to-list 'load-path "D:/Programs/Lean/lean-0.2.0-windows/share/emacs/site-lisp/lean")
```

explicitly to `.emacs`, it does work without complaining. Could there be a problem with the syntax `\\/..` in the above path?

---

One last thing: I added the above hack to my `.emacs` file, but now I think the variable `lean-rootdir` is wrong. When I execute a lean file (`C-c C-x`) I get the error

```
"d:/lean-0.2.0-windows/bin/lean.exe" -Dpp.width=120  "d:/Programs/Lean/lean-0.2.0-windows/lib/lean/library/data/bag.lean"
The system cannot find the path specified.
```

The path to `lean.exe` is wrong, it should be d:/**Programs/Lean/**lean-0.2.0-windows/bin/lean.exe. The output of `C-h v lean-rootdir` is

```
lean-rootdir is a variable defined in `lean-settings.el'.
Its value is "\\lean-0.2.0-windows"
Original value was nil

Documentation:
Full pathname of lean root directory. It should be defined by user.

You can customize this variable.
```

Once again, manually changing my `.emacs` file does fix the problem, but the instructions on [this page](https://github.com/leanprover/lean/blob/master/src/emacs/README.md) should be changed. It would be especially nice if there was a solution so that the user can just copy-paste some code, without manual changes. I tried some variants, but I couldn't work out in either of the above cases to do it.

**Comment by fpvandoorn** [comment] 2015-10-01 03:28
About the `load-path`, I wasn't very clear. First of all `\\/..` isn't a problem. If I explicitly add

```
(add-to-list 'load-path "D:\\Programs\\Lean\\lean-0.2.0-windows\\bin\\/../share/emacs/site-lisp/lean")
```

it's also fine.

The problem is that the path to `lean-mode` is actually wrong. If I just copy paste the code for the `.emacs` file (according to the instructions in the README), and open Emacs (i.e. _not_ `leanemacs.bat`) then my load path is

```
load-path is a variable defined in `C source code'.
Its value is
("d:/lean-0.2.0-windows/share/emacs/site-lisp/lean" [...])
```

So it misses the `Programs/Lean` part of the path.

If I open Emacs using `leanemacs.bat` the `load-path` contains a whole lot of other folders (probably as specified by `load-lean.el`, but I guess that `.emacs` cannot find `lean-mode` because it is executed before `load-lean.el` is executed.

**Comment by soonhokong** [comment] 2015-10-01 20:03
@fpvandoorn, thanks for notes. I'll check things up tonight.

**Comment by leodemoura** [comment] 2016-12-01 22:04
The latest version works on Win 10 without problems.

**Closed as completed by leodemoura** 2016-12-01 22:04 UTC
