### ISSUE TITLE
Transfer does not work with universe metavariables

### ISSUE THREAD

**Issue by gebner** [leanprover/lean3#1535] opened 2017-04-23 16:55 UTC
The following snippet fails at `dlist.transfer`, but works as soon as I change `Type _` to `Type u`.
```lean
import data.dlist
universe u

example (α : Type _) (a b c : dlist α) : (a ++ b) ++ c = (a ++ b) ++ c :=
begin
revert a b c,
dlist.transfer,
intros,
simp,
end
```

**Comment by leodemoura** [comment] 2017-04-23 17:07
@gebner Note that it works if we use `lemma` instead of `example`.
It works because we fully elaborate the lemma/theorem type before we process the body.
So, all universe meta-variables have been already resolved and assigned to universe parameters.

One easy solution is for `transfer` to sign an error message if the context contains universe meta-variables. I don't think this is a big limitation. 

@johoelzl: If the limitation above is easy to remove, then, of course, it is a better solution.

**Comment by Kha** [comment] 2017-04-23 17:54
@leodemoura
> It works because we fully elaborate the lemma/theorem type before we process the body.

Should we do that for every declaration that has an explicit type? Or is there code that depends on this?
If we change it, would it be a good idea to make even elaborating definitions async?

**Comment by leodemoura** [comment] 2017-04-23 17:59
> Should we do that for every declaration that has an explicit type?

@kha I think this is a good idea.

> Or is there code that depends on this?
> If we change it, would it be a good idea to make even elaborating definitions async?

I think this is feasible, but we would have to use `task`s for definitions too.
@gebner Do you see problems?

**Comment by johoelzl** [comment] 2017-04-23 17:59
Might be a simple bug. I guess I just need to handle the meta variables like a local variable. I will investigate it tomorrow.

**Comment by gebner** [comment] 2017-04-23 18:41
> I think this is feasible, but we would have to use tasks for definitions too.
> @gebner Do you see problems?

I see two issues:
1) Is it clear how this would interact with `variables`?
2) Making definitions async would require us to make lots of other changes:
  * We would need to make VM compilation async as well.  Creating a `vm_state` must not wait for any definition that is not executed.
  * How we would we declare equations for async definitions?
  * Quite a few declarations would need to wait for some definition to finish elaborating.  (Just type-checking the type can require delta-reduction.)  I have no empirical data on how bad this would get in practice.  Remember, every time we wait for something we need an extra thread.
  * Noncomputability annotations would also need to be computed async.

**Comment by leodemoura** [comment] 2017-04-23 18:44
@gebner Thanks for the feedback. I retract my comment: "I think this is feasible".

**Comment by johoelzl** [comment] 2017-04-24 17:43
The problem is that I use the type class mechanism to compute the relation to transfer the forall-quantifier. When it transfers the quantifier it needs to find a bi-total relation, it uses `apply_instance`.

With the universe is fixed `transfer` requests the following:
  `@relator.bi_total.{u ?l_1} (dlist.{u} α) ?m_3 ?m_4`
the level `?l_1` is instantiated by instantiating `?m_3` and `?m_4` which are fine as they are `out_param`s.

When the universe is a meta variable the request looks as follows:
  `@relator.bi_total.{?l_1 ?l_2} (dlist.{?l_1} α) ?m_3 ?m_4`

Is it possible to setup the elaborator to cope with these levels?

I can just report and error if a meta variable appears.

Alternatively: Would it make sense to have a tactical, which 
 * creates local variables for all meta variables
 * calls a tactic operating on the goal
 * replaces afterwards the local variables by meta variables again
 * add new goals for meta variables which disappeared from the goal

Does this make sense? How does the simplifier cope with this problem?

**Comment by leodemoura** [comment] 2017-04-29 19:20
@johoelzl Should we close this issue? Your commit seems to address the problem, right?

**Comment by johoelzl** [comment] 2017-04-30 22:01
Yes you can close it. My commit addresses the current problem.

When people have use cases where meta variables appear in the goal, then I will think about temporarily replacing meta variables with local variables.

**Closed as completed** 2017-04-30 22:01 UTC
